In [16]:
import requests #Used to service API connection
from lxml import html #Used to parse XML
from bs4 import BeautifulSoup #Used to read XML table on webpage
import pandas as pd
#from pandas import DataFrame
import numpy as np
import wget
from common import cFunction as cf


# get dataList from filesystem to load and write
#dataList = pd.read_excel("../../data/inbound/dataList.xlsx")

In [17]:
# get dataList from spreadsheet to load and write
dataList = pd.read_csv("../../data/inbound/workSheet.csv")
print("### The total number of target data is " + str(len(dataList)))

### The total number of target data is 417

In [18]:
regionCdData = pd.read_csv("../../data/infomations/RegionCode.csv")
print(regionCdData)

    순번  지역     코드
0    1  서울  11000
1    2  부산  26000
2    3  대구  27000
3    4  인천  28000
4    5  광주  29000
5    6  대전  30000
6    7  울산  31000
7    8  경기  41000
8    9  강원  42000
9   10  축북  43000
10  11  충남  44000
11  12  전북  45000
12  13  전남  46000
13  14  경북  47000
14  15  경남  48000
15  16  제주  50000

In [19]:
# Filtering -> get dataList only defined url
dataList = dataList[(dataList["제공항목(데이터셋)"] == '한국감정원 주택거래 현황') & (dataList["제공방식"] == 'OPENAPI')]
print("### The total number of filtered data is " + str(len(dataList)))
dataList

### The total number of filtered data is 1

,번호,접속 사이트,제공항목(데이터셋),폴더명,작업자,시작일,종료일,검토자,진행상태,비고,...,파라미터,제공방식.1,데이터타입,참고문서,참고문서타입,주기,비고_파라미터설명,완료여부,API PGM ID,파일명
354,355,공공데이터포털,한국감정원 주택거래 현황,354_한국감정원 주택거래 현황,NaN,NaN,NaN,NaN,NaN,NaN,...,startmonth=200601&endmonth=201903&region=11000,api,xml,https://www.data.go.kr/comm/file/download.do?a...,NaN,NaN,NaN,완료,TB_OD10354.py,TB_OD10354_yyyymm.csv

In [20]:
###################################################
# Filtering -> for your own object
#dataList = dataList[   dataList['번호'] == "352" ]
###################################################

# create folder to save result
outPath = "../../data/outbound/"
folderList = dataList["폴더명"].tolist()

In [21]:
for i in folderList:
    cf.createFolder(outPath+i)

In [22]:
dataList = dataList.fillna("")
dataList = dataList.reset_index(drop=True)
dataList

,번호,접속 사이트,제공항목(데이터셋),폴더명,작업자,시작일,종료일,검토자,진행상태,비고,...,파라미터,제공방식.1,데이터타입,참고문서,참고문서타입,주기,비고_파라미터설명,완료여부,API PGM ID,파일명
0,355,공공데이터포털,한국감정원 주택거래 현황,354_한국감정원 주택거래 현황,,,,,,,...,startmonth=200601&endmonth=201903&region=11000,api,xml,https://www.data.go.kr/comm/file/download.do?a...,,,,완료,TB_OD10354.py,TB_OD10354_yyyymm.csv

In [23]:
dataCount = 0

In [24]:
# get dataList to load and write
inputUrl = dataList.loc[dataCount, "사이트"]
inputKey = dataList.loc[dataCount, "서비스키"]
inputParameter = dataList.loc[dataCount, "파라미터"]
inputFolder = dataList.loc[dataCount, "폴더명"]
inputFile = dataList.loc[dataCount, "서비스명"]
inputDataType = dataList.loc[dataCount, "데이터타입"]
inputRefUrl = dataList.loc[dataCount, "참고문서"]
inputRefType = dataList.loc[dataCount, "참고문서타입"]
inputbParameter = dataList.loc[dataCount, "비고_파라미터설명"]
len(inputbParameter)

0

In [25]:
url = cf.makeURL(inputUrl,inputKey,inputParameter)
print("fullUrl is " + url)

fullUrl is http://openapi.kab.co.kr/OpenAPI_ToolInstallPackage/service/rest/AptTradingStateSvc/getAptTrdStateCaseOfNbr?&serviceKey=aiaNgZ3r3nPeUj5%2FKuJ10ZNRmyePXavavOu8RZwO%2F84LnOn5KxhWa1%2F5nwxk0Y4M10W0fjCK1SksOQeQsdMu6A%3D%3D&startmonth=200601&endmonth=201903&region=11000

In [26]:
newDF = pd.DataFrame()
if (inputDataType == "xml"):
    newDF = cf.operatorXmlProcess(url, inputbParameter)
elif(inputDataType == "json"):
    newDF = cf.jsonProcess(url)
elif(inputDataType == "csv"):
    newDF = cf.csvProcess(url)

  regionCd regionNm                                              rsRow
0    11000       서울  200601,7704|200602,12717|200603,17419|200604,1...
  regionCd regionNm                                              rsRow
0    26000       부산  200601,4592|200602,6064|200603,6482|200604,583...
  regionCd regionNm                                              rsRow
0    27000       대구  200601,3684|200602,4797|200603,4925|200604,437...
  regionCd regionNm                                              rsRow
0    28000       인천  200601,2143|200602,3948|200603,4482|200604,413...
  regionCd regionNm                                              rsRow
0    29000       광주  200601,3782|200602,3928|200603,5297|200604,444...
  regionCd regionNm                                              rsRow
0    30000       대전  200601,2112|200602,3072|200603,5838|200604,312...
  regionCd regionNm                                              rsRow
0    31000       울산  200601,1435|200602,2388|200603,2531|200604,247...
  regionCd regionNm                                              rsRow
0    41000       경기  200601,17630|200602,20561|200603,28400|200604,...
  regionCd regionNm                                              rsRow
0    42000       강원  200601,1982|200602,2690|200603,3307|200604,222...
  regionCd regionNm                                              rsRow
0    43000       충북  200601,1383|200602,3003|200603,2964|200604,180...
  regionCd regionNm                                              rsRow
0    44000       충남  200601,2558|200602,3501|200603,4268|200604,357...
  regionCd regionNm                                              rsRow
0    45000       전북  200601,2021|200602,2375|200603,2668|200604,291...
  regionCd regionNm                                              rsRow
0    46000       전남  200601,780|200602,1134|200603,1803|200604,1650...
  regionCd regionNm                                              rsRow
0    47000       경북  200601,4010|200602,4680|200603,4286|200604,397...
  regionCd regionNm                                              rsRow
0    48000       경남  200601,4897|200602,4950|200603,4766|200604,445...
  regionCd regionNm                                              rsRow
0    50000       제주  200607,124|200608,135|200609,277|200610,317|20...

C:\ProgramData\Anaconda3\lib\site-packages\common\cFunction.py:77: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  mergeData = pd.concat([mergeData, newDF], axis=0)

In [27]:
newDF

     regionCd regionNm yearMonth volume
0       11000       서울    200601   7704
1       11000       서울    200602  12717
2       11000       서울    200603  17419
3       11000       서울    200604  14919
4       11000       서울    200605  16277
5       11000       서울    200606  11574
6       11000       서울    200607   8649
7       11000       서울    200608   8463
8       11000       서울    200609  15880
9       11000       서울    200610  22346
10      11000       서울    200611  27800
11      11000       서울    200612  18551
12      11000       서울    200701   9411
13      11000       서울    200702   5971
14      11000       서울    200703   7430
15      11000       서울    200704   7461
16      11000       서울    200705   6422
17      11000       서울    200706   6456
18      11000       서울    200707   7018
19      11000       서울    200708   6862
20      11000       서울    200709   6303
21      11000       서울    200710   8522
22      11000       서울    200711   8918
23      11000       서울    200712   7674
24      11000       서울    200801   7233
25      11000       서울    200802   6953
26      11000       서울    200803  10746
27      11000       서울    200804  13590
28      11000       서울    200805  10041
29      11000       서울    200806   9417
...       ...      ...       ...    ...
2514    50000       제주    201610    452
2515    50000       제주    201611    695
2516    50000       제주    201612    775
2517    50000       제주    201701    824
2518    50000       제주    201702    759
2519    50000       제주    201703    661
2520    50000       제주    201704    623
2521    50000       제주    201705    468
2522    50000       제주    201706    528
2523    50000       제주    201707    427
2524    50000       제주    201708    469
2525    50000       제주    201709    547
2526    50000       제주    201710    444
2527    50000       제주    201711    648
2528    50000       제주    201712    692
2529    50000       제주    201801    570
2530    50000       제주    201802    622
2531    50000       제주    201803    602
2532    50000       제주    201804    605
2533    50000       제주    201805    410
2534    50000       제주    201806    823
2535    50000       제주    201807    716
2536    50000       제주    201808    501
2537    50000       제주    201809    328
2538    50000       제주    201810    457
2539    50000       제주    201811    455
2540    50000       제주    201812    478
2541    50000       제주    201901    701
2542    50000       제주    201902    516
2543    50000       제주    201903    323

[2544 rows x 4 columns]

In [28]:
fullOutPath = outPath+inputFolder+"/"+inputFolder+inputFile+".csv"
print(fullOutPath)

../../data/outbound/354_한국감정원 주택거래 현황/354_한국감정원 주택거래 현황.csv

In [29]:
try:
    newDF.to_csv(fullOutPath, index=False, encoding="ms949")
except Exception as x:
    print(x)

In [30]:
fullOutRefPath = outPath + inputFolder + "/" + inputFolder + inputFile + "."+inputRefType
try:
    wget.download(inputRefUrl, fullOutRefPath)
except Exception as e:
    print(inputFolder+"참고문서 Error")
    print(e)
    pass

100% [........................................................] 550930 / 550930