In [1]:
import pandas as pd
selloutData = pd.read_csv('./Python_Fintech/Python_ST_EX/dataset/kopo_channel_seasonality_new.csv')

In [2]:
selloutData.head()

  REGIONID    PRODUCT  YEARWEEK      QTY
0      A60   PRODUCT4    201402     71.0
1      A60  PRODUCT59    201402  22275.0
2      A60  PRODUCT34    201402   4463.0
3      A60  PRODUCT47    201402      0.0
4      A60  PRODUCT56    201402     23.0

In [3]:
import numpy as np
selloutData['NEW_QTY'] = np.where(selloutData.QTY < 0, 0, selloutData.QTY)

In [4]:
selloutData[selloutData.NEW_QTY < 0]

Empty DataFrame
Columns: [REGIONID, PRODUCT, YEARWEEK, QTY, NEW_QTY]
Index: []

In [5]:
selloutData.dtypes

REGIONID     object
PRODUCT      object
YEARWEEK      int64
QTY         float64
NEW_QTY     float64
dtype: object

In [6]:
def customFunction(inputColumn):
    return inputColumn // 100

In [7]:
selloutData['YEAR'] = customFunction(selloutData.YEARWEEK)

In [8]:
selloutData['WEEK'] = selloutData.YEARWEEK % 100

In [9]:
selloutData.head()

  REGIONID    PRODUCT  YEARWEEK      QTY  NEW_QTY  YEAR  WEEK
0      A60   PRODUCT4    201402     71.0     71.0  2014     2
1      A60  PRODUCT59    201402  22275.0  22275.0  2014     2
2      A60  PRODUCT34    201402   4463.0   4463.0  2014     2
3      A60  PRODUCT47    201402      0.0      0.0  2014     2
4      A60  PRODUCT56    201402     23.0     23.0  2014     2

In [10]:
refinedData = selloutData[selloutData.WEEK <= 52]

In [11]:
refinedData.head()

  REGIONID    PRODUCT  YEARWEEK      QTY  NEW_QTY  YEAR  WEEK
0      A60   PRODUCT4    201402     71.0     71.0  2014     2
1      A60  PRODUCT59    201402  22275.0  22275.0  2014     2
2      A60  PRODUCT34    201402   4463.0   4463.0  2014     2
3      A60  PRODUCT47    201402      0.0      0.0  2014     2
4      A60  PRODUCT56    201402     23.0     23.0  2014     2

In [12]:
sortKey = ['REGIONID', 'PRODUCT', 'YEARWEEK']
sortedData = refinedData.sort_values(sortKey)
sortedData.head()

     REGIONID    PRODUCT  YEARWEEK    QTY  NEW_QTY  YEAR  WEEK
298       A00  PRODUCT34    201401  661.0    661.0  2014     1
1757      A00  PRODUCT34    201402  679.0    679.0  2014     2
3125      A00  PRODUCT34    201403  578.0    578.0  2014     3
205       A00  PRODUCT34    201404  532.0    532.0  2014     4
4369      A00  PRODUCT34    201405  516.0    516.0  2014     5

In [13]:
sortedData = sortedData.reset_index(drop = True)
sortedData.head()

  REGIONID    PRODUCT  YEARWEEK    QTY  NEW_QTY  YEAR  WEEK
0      A00  PRODUCT34    201401  661.0    661.0  2014     1
1      A00  PRODUCT34    201402  679.0    679.0  2014     2
2      A00  PRODUCT34    201403  578.0    578.0  2014     3
3      A00  PRODUCT34    201404  532.0    532.0  2014     4
4      A00  PRODUCT34    201405  516.0    516.0  2014     5

In [14]:
sortedData['MA'] = sortedData.NEW_QTY.rolling(window = 15, center = True, min_periods = 1).mean()
sortedData

,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA
0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000
1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444
2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000
3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636
4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000
5,A00,PRODUCT34,201406,423.0,423.0,2014,6,480.230769
6,A00,PRODUCT34,201407,407.0,407.0,2014,7,468.214286
7,A00,PRODUCT34,201408,364.0,364.0,2014,8,456.666667
8,A00,PRODUCT34,201409,470.0,470.0,2014,9,431.533333
9,A00,PRODUCT34,201410,538.0,538.0,2014,10,402.066667
10,A00,PRODUCT34,201411,369.0,369.0,2014,11,375.533333
11,A00,PRODUCT34,201412,352.0,352.0,2014,12,350.800000
12,A00,PRODUCT34,201413,354.0,354.0,2014,13,325.733333
13,A00,PRODUCT34,201414,312.0,312.0,2014,14,305.266667
14,A00,PRODUCT34,201415,295.0,295.0,2014,15,284.666667
15,A00,PRODUCT34,201416,284.0,284.0,2014,16,265.933333
16,A00,PRODUCT34,201417,237.0,237.0,2014,17,239.333333
17,A00,PRODUCT34,201418,180.0,180.0,2014,18,207.800000
18,A00,PRODUCT34,201419,161.0,161.0,2014,19,187.200000
19,A00,PRODUCT34,201420,140.0,140.0,2014,20,169.200000
20,A00,PRODUCT34,201421,116.0,116.0,2014,21,155.666667
21,A00,PRODUCT34,201422,98.0,98.0,2014,22,153.133333
22,A00,PRODUCT34,201423,83.0,83.0,2014,23,168.933333
23,A00,PRODUCT34,201424,71.0,71.0,2014,24,179.933333
24,A00,PRODUCT34,201425,65.0,65.0,2014,25,193.000000
25,A00,PRODUCT34,201426,60.0,60.0,2014,26,205.266667
26,A00,PRODUCT34,201427,82.0,82.0,2014,27,217.600000
27,A00,PRODUCT34,201428,151.0,151.0,2014,28,229.066667
28,A00,PRODUCT34,201429,274.0,274.0,2014,29,237.600000
29,A00,PRODUCT34,201430,532.0,532.0,2014,30,246.200000
...,...,...,...,...,...,...,...,...
123834,A77,PRODUCT12,201623,5348.0,5348.0,2016,23,4159.933333
123835,A77,PRODUCT12,201624,3275.0,3275.0,2016,24,4272.333333
123836,A77,PRODUCT12,201625,4158.0,4158.0,2016,25,4435.133333
123837,A77,PRODUCT12,201626,4815.0,4815.0,2016,26,4530.533333
123838,A77,PRODUCT12,201627,3002.0,3002.0,2016,27,4518.466667
123839,A77,PRODUCT12,201628,3319.0,3319.0,2016,28,4527.000000
123840,A77,PRODUCT12,201629,4200.0,4200.0,2016,29,4528.533333
123841,A77,PRODUCT12,201630,7120.0,7120.0,2016,30,4402.866667
123842,A77,PRODUCT12,201631,6345.0,6345.0,2016,31,4418.533333
123843,A77,PRODUCT12,201632,5863.0,5863.0,2016,32,5182.466667
123844,A77,PRODUCT12,201633,4211.0,4211.0,2016,33,5145.466667
123845,A77,PRODUCT12,201634,4019.0,4019.0,2016,34,5091.800000
123846,A77,PRODUCT12,201635,3624.0,3624.0,2016,35,5177.800000
123847,A77,PRODUCT12,201636,3742.0,3742.0,2016,36,5340.533333
123848,A77,PRODUCT12,201637,3002.0,3002.0,2016,37,5334.466667
123849,A77,PRODUCT12,201638,5583.0,5583.0,2016,38,5160.200000
123850,A77,PRODUCT12,201639,14734.0,14734.0,2016,39,5020.866667
123851,A77,PRODUCT12,201640,3603.0,3603.0,2016,40,4868.266667
123852,A77,PRODUCT12,201641,4010.0,4010.0,2016,41,4864.333333
123853,A77,PRODUCT12,201642,4292.0,4292.0,2016,42,4935.466667
123854,A77,PRODUCT12,201643,5760.0,5760.0,2016,43,5083.600000
123855,A77,PRODUCT12,201644,4109.0,4109.0,2016,44,5163.000000
123856,A77,PRODUCT12,201645,4506.0,4506.0,2016,45,5466.266667
123857,A77,PRODUCT12,201646,4255.0,4255.0,2016,46,5457.928571
123858,A77,PRODUCT12,201647,3574.0,3574.0,2016,47,4744.384615
123859,A77,PRODUCT12,201648,4152.0,4152.0,2016,48,4839.500000
123860,A77,PRODUCT12,201649,5086.0,5086.0,2016,49,4914.909091
123861,A77,PRODUCT12,201650,5846.0,5846.0,2016,50,4977.200000
123862,A77,PRODUCT12,201651,4933.0,4933.0,2016,51,4890.222222
123863,A77,PRODUCT12,201652,7551.0,7551.0,2016,52,4987.875000

In [15]:
sortedData.to_csv('result.csv')

In [16]:
filteredData = sortedData[(sortedData.REGIONID == 'A00') & (sortedData.PRODUCT == 'PRODUCT34')]

In [17]:
filteredData.head()

  REGIONID    PRODUCT  YEARWEEK    QTY  NEW_QTY  YEAR  WEEK          MA
0      A00  PRODUCT34    201401  661.0    661.0  2014     1  520.000000
1      A00  PRODUCT34    201402  679.0    679.0  2014     2  514.444444
2      A00  PRODUCT34    201403  578.0    578.0  2014     3  516.800000
3      A00  PRODUCT34    201404  532.0    532.0  2014     4  503.363636
4      A00  PRODUCT34    201405  516.0    516.0  2014     5  490.750000

In [120]:
filteredData.groupby(['REGIONID', 'PRODUCT', 'YEAR'])[['NEW_QTY']]

In [19]:
groupData = sortedData.groupby(['REGIONID', 'PRODUCT', 'YEAR'])[['NEW_QTY']].mean()

In [20]:
groupDataResult = groupData.reset_index()
groupDataResult.head()

  REGIONID    PRODUCT  YEAR     NEW_QTY
0      A00  PRODUCT34  2014  275.961538
1      A00  PRODUCT34  2015   86.634615
2      A00  PRODUCT34  2016   36.576923
3      A00  PRODUCT58  2014    2.673077
4      A00  PRODUCT58  2015    5.711538

In [21]:
groupDataResult.columns = ['REGIONID', 'PRODUCT', 'YEAR', 'GROUP']
groupDataResult.head()

  REGIONID    PRODUCT  YEAR       GROUP
0      A00  PRODUCT34  2014  275.961538
1      A00  PRODUCT34  2015   86.634615
2      A00  PRODUCT34  2016   36.576923
3      A00  PRODUCT58  2014    2.673077
4      A00  PRODUCT58  2015    5.711538

In [22]:
mergedData = pd.merge(filteredData, groupDataResult, left_on = ['REGIONID', 'PRODUCT', 'YEAR'], right_on = ['REGIONID', 'PRODUCT', 'YEAR'], how = 'left')\

In [23]:
filteredData['SEASONALITY'] = filteredData['NEW_QTY'] / filteredData['MA']
filteredData.head()

C:\Users\SMART-08\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,SEASONALITY
0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000,1.271154
1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444,1.319870
2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000,1.118421
3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636,1.056890
4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000,1.051452

In [24]:
filteredData.head()

,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,SEASONALITY
0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000,1.271154
1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444,1.319870
2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000,1.118421
3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636,1.056890
4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000,1.051452

In [25]:
mergedData

,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,GROUP
0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000,275.961538
1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444,275.961538
2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000,275.961538
3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636,275.961538
4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000,275.961538
5,A00,PRODUCT34,201406,423.0,423.0,2014,6,480.230769,275.961538
6,A00,PRODUCT34,201407,407.0,407.0,2014,7,468.214286,275.961538
7,A00,PRODUCT34,201408,364.0,364.0,2014,8,456.666667,275.961538
8,A00,PRODUCT34,201409,470.0,470.0,2014,9,431.533333,275.961538
9,A00,PRODUCT34,201410,538.0,538.0,2014,10,402.066667,275.961538
10,A00,PRODUCT34,201411,369.0,369.0,2014,11,375.533333,275.961538
11,A00,PRODUCT34,201412,352.0,352.0,2014,12,350.800000,275.961538
12,A00,PRODUCT34,201413,354.0,354.0,2014,13,325.733333,275.961538
13,A00,PRODUCT34,201414,312.0,312.0,2014,14,305.266667,275.961538
14,A00,PRODUCT34,201415,295.0,295.0,2014,15,284.666667,275.961538
15,A00,PRODUCT34,201416,284.0,284.0,2014,16,265.933333,275.961538
16,A00,PRODUCT34,201417,237.0,237.0,2014,17,239.333333,275.961538
17,A00,PRODUCT34,201418,180.0,180.0,2014,18,207.800000,275.961538
18,A00,PRODUCT34,201419,161.0,161.0,2014,19,187.200000,275.961538
19,A00,PRODUCT34,201420,140.0,140.0,2014,20,169.200000,275.961538
20,A00,PRODUCT34,201421,116.0,116.0,2014,21,155.666667,275.961538
21,A00,PRODUCT34,201422,98.0,98.0,2014,22,153.133333,275.961538
22,A00,PRODUCT34,201423,83.0,83.0,2014,23,168.933333,275.961538
23,A00,PRODUCT34,201424,71.0,71.0,2014,24,179.933333,275.961538
24,A00,PRODUCT34,201425,65.0,65.0,2014,25,193.000000,275.961538
25,A00,PRODUCT34,201426,60.0,60.0,2014,26,205.266667,275.961538
26,A00,PRODUCT34,201427,82.0,82.0,2014,27,217.600000,275.961538
27,A00,PRODUCT34,201428,151.0,151.0,2014,28,229.066667,275.961538
28,A00,PRODUCT34,201429,274.0,274.0,2014,29,237.600000,275.961538
29,A00,PRODUCT34,201430,532.0,532.0,2014,30,246.200000,275.961538
...,...,...,...,...,...,...,...,...,...
126,A00,PRODUCT34,201623,7.0,7.0,2016,23,34.600000,36.576923
127,A00,PRODUCT34,201624,7.0,7.0,2016,24,34.533333,36.576923
128,A00,PRODUCT34,201625,5.0,5.0,2016,25,39.733333,36.576923
129,A00,PRODUCT34,201626,7.0,7.0,2016,26,39.200000,36.576923
130,A00,PRODUCT34,201627,3.0,3.0,2016,27,39.333333,36.576923
131,A00,PRODUCT34,201628,19.0,19.0,2016,28,39.066667,36.576923
132,A00,PRODUCT34,201629,419.0,419.0,2016,29,38.800000,36.576923
133,A00,PRODUCT34,201630,6.0,6.0,2016,30,38.866667,36.576923
134,A00,PRODUCT34,201631,7.0,7.0,2016,31,45.133333,36.576923
135,A00,PRODUCT34,201632,82.0,82.0,2016,32,82.066667,36.576923
136,A00,PRODUCT34,201633,2.0,2.0,2016,33,82.866667,36.576923
137,A00,PRODUCT34,201634,8.0,8.0,2016,34,87.400000,36.576923
138,A00,PRODUCT34,201635,4.0,4.0,2016,35,87.866667,36.576923
139,A00,PRODUCT34,201636,2.0,2.0,2016,36,87.333333,36.576923
140,A00,PRODUCT34,201637,5.0,5.0,2016,37,60.400000,36.576923
141,A00,PRODUCT34,201638,101.0,101.0,2016,38,61.200000,36.576923
142,A00,PRODUCT34,201639,561.0,561.0,2016,39,61.666667,36.576923
143,A00,PRODUCT34,201640,17.0,17.0,2016,40,56.800000,36.576923
144,A00,PRODUCT34,201641,75.0,75.0,2016,41,57.800000,36.576923
145,A00,PRODUCT34,201642,10.0,10.0,2016,42,58.533333,36.576923
146,A00,PRODUCT34,201643,11.0,11.0,2016,43,60.600000,36.576923
147,A00,PRODUCT34,201644,15.0,15.0,2016,44,65.333333,36.576923
148,A00,PRODUCT34,201645,18.0,18.0,2016,45,66.466667,36.576923
149,A00,PRODUCT34,201646,14.0,14.0,2016,46,59.733333,36.576923
150,A00,PRODUCT34,201647,9.0,9.0,2016,47,22.333333,36.576923
151,A00,PRODUCT34,201648,17.0,17.0,2016,48,21.200000,36.576923
152,A00,PRODUCT34,201649,19.0,19.0,2016,49,16.200000,36.576923
153,A00,PRODUCT34,201650,35.0,35.0,2016,50,15.533333,36.576923
154,A00,PRODUCT34,201651,73.0,73.0,2016,51,14.800000,36.576923
155,A00,PRODUCT34,201652,22.0,22.0,2016,52,13.800000,36.576923

In [26]:
filteredData.dtypes

REGIONID        object
PRODUCT         object
YEARWEEK         int64
QTY            float64
NEW_QTY        float64
YEAR             int64
WEEK             int64
MA             float64
SEASONALITY    float64
dtype: object

In [27]:
filteredData.head()

,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,SEASONALITY
0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000,1.271154
1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444,1.319870
2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000,1.118421
3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636,1.056890
4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000,1.051452

In [28]:
groupDataResult.head()

  REGIONID    PRODUCT  YEAR       GROUP
0      A00  PRODUCT34  2014  275.961538
1      A00  PRODUCT34  2015   86.634615
2      A00  PRODUCT34  2016   36.576923
3      A00  PRODUCT58  2014    2.673077
4      A00  PRODUCT58  2015    5.711538

In [29]:
len(mergedData)

156

In [30]:
len(filteredData)

156

In [31]:
sortedData.head()

  REGIONID    PRODUCT  YEARWEEK    QTY  NEW_QTY  YEAR  WEEK          MA
0      A00  PRODUCT34    201401  661.0    661.0  2014     1  520.000000
1      A00  PRODUCT34    201402  679.0    679.0  2014     2  514.444444
2      A00  PRODUCT34    201403  578.0    578.0  2014     3  516.800000
3      A00  PRODUCT34    201404  532.0    532.0  2014     4  503.363636
4      A00  PRODUCT34    201405  516.0    516.0  2014     5  490.750000

In [32]:
sortedData['SEASONALITY'] = sortedData['NEW_QTY'] / sortedData['MA']
sortedData.head()

,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,SEASONALITY
0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000,1.271154
1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444,1.319870
2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000,1.118421
3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636,1.056890
4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000,1.051452

In [33]:
sortedData.head()

,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,SEASONALITY
0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000,1.271154
1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444,1.319870
2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000,1.118421
3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636,1.056890
4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000,1.051452

In [34]:
groupDataResult.head()

  REGIONID    PRODUCT  YEAR       GROUP
0      A00  PRODUCT34  2014  275.961538
1      A00  PRODUCT34  2015   86.634615
2      A00  PRODUCT34  2016   36.576923
3      A00  PRODUCT58  2014    2.673077
4      A00  PRODUCT58  2015    5.711538

In [35]:
mergedData = pd.merge(sortedData, groupDataResult, on = ['REGIONID', 'PRODUCT', 'YEAR'], how = 'left')\
[['REGIONID', 'PRODUCT', 'YEARWEEK', 'QTY', 'NEW_QTY', 'YEAR', 'WEEK', 'MA', 'GROUP', 'SEASONALITY']]
mergedData.head()

,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,GROUP,SEASONALITY
0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000,275.961538,1.271154
1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444,275.961538,1.319870
2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000,275.961538,1.118421
3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636,275.961538,1.056890
4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000,275.961538,1.051452

In [36]:
mergedData.columns = [['REGIONID', 'PRODUCT', 'YEARWEEK', 'QTY', 'NEW_QTY', 'YEAR', 'WEEK', 'MA', 'QTY_MEAN_YEAR', 'SEASONALITY']]
mergedData.head()

,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,QTY_MEAN_YEAR,SEASONALITY
0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000,275.961538,1.271154
1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444,275.961538,1.319870
2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000,275.961538,1.118421
3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636,275.961538,1.056890
4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000,275.961538,1.051452

In [37]:
mergedData.to_csv("./merge.csv")

In [38]:
mergedData.dtypes

REGIONID          object
PRODUCT           object
YEARWEEK           int64
QTY              float64
NEW_QTY          float64
YEAR               int64
WEEK               int64
MA               float64
QTY_MEAN_YEAR    float64
SEASONALITY      float64
dtype: object

In [39]:
testData = pd.read_csv("./merge.csv")

In [40]:
groupKey2 = ['REGIONID', 'PRODUCT']

In [41]:
groupDataSet = testData.groupby(groupKey2)
groupDataSet

In [42]:
mergedData

,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,QTY_MEAN_YEAR,SEASONALITY
0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000,275.961538,1.271154
1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444,275.961538,1.319870
2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000,275.961538,1.118421
3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636,275.961538,1.056890
4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000,275.961538,1.051452
5,A00,PRODUCT34,201406,423.0,423.0,2014,6,480.230769,275.961538,0.880827
6,A00,PRODUCT34,201407,407.0,407.0,2014,7,468.214286,275.961538,0.869260
7,A00,PRODUCT34,201408,364.0,364.0,2014,8,456.666667,275.961538,0.797080
8,A00,PRODUCT34,201409,470.0,470.0,2014,9,431.533333,275.961538,1.089140
9,A00,PRODUCT34,201410,538.0,538.0,2014,10,402.066667,275.961538,1.338087
10,A00,PRODUCT34,201411,369.0,369.0,2014,11,375.533333,275.961538,0.982603
11,A00,PRODUCT34,201412,352.0,352.0,2014,12,350.800000,275.961538,1.003421
12,A00,PRODUCT34,201413,354.0,354.0,2014,13,325.733333,275.961538,1.086779
13,A00,PRODUCT34,201414,312.0,312.0,2014,14,305.266667,275.961538,1.022057
14,A00,PRODUCT34,201415,295.0,295.0,2014,15,284.666667,275.961538,1.036300
15,A00,PRODUCT34,201416,284.0,284.0,2014,16,265.933333,275.961538,1.067937
16,A00,PRODUCT34,201417,237.0,237.0,2014,17,239.333333,275.961538,0.990251
17,A00,PRODUCT34,201418,180.0,180.0,2014,18,207.800000,275.961538,0.866218
18,A00,PRODUCT34,201419,161.0,161.0,2014,19,187.200000,275.961538,0.860043
19,A00,PRODUCT34,201420,140.0,140.0,2014,20,169.200000,275.961538,0.827423
20,A00,PRODUCT34,201421,116.0,116.0,2014,21,155.666667,275.961538,0.745182
21,A00,PRODUCT34,201422,98.0,98.0,2014,22,153.133333,275.961538,0.639965
22,A00,PRODUCT34,201423,83.0,83.0,2014,23,168.933333,275.961538,0.491318
23,A00,PRODUCT34,201424,71.0,71.0,2014,24,179.933333,275.961538,0.394591
24,A00,PRODUCT34,201425,65.0,65.0,2014,25,193.000000,275.961538,0.336788
25,A00,PRODUCT34,201426,60.0,60.0,2014,26,205.266667,275.961538,0.292303
26,A00,PRODUCT34,201427,82.0,82.0,2014,27,217.600000,275.961538,0.376838
27,A00,PRODUCT34,201428,151.0,151.0,2014,28,229.066667,275.961538,0.659197
28,A00,PRODUCT34,201429,274.0,274.0,2014,29,237.600000,275.961538,1.153199
29,A00,PRODUCT34,201430,532.0,532.0,2014,30,246.200000,275.961538,2.160845
...,...,...,...,...,...,...,...,...,...,...
123834,A77,PRODUCT12,201623,5348.0,5348.0,2016,23,4159.933333,4837.153846,1.285598
123835,A77,PRODUCT12,201624,3275.0,3275.0,2016,24,4272.333333,4837.153846,0.766560
123836,A77,PRODUCT12,201625,4158.0,4158.0,2016,25,4435.133333,4837.153846,0.937514
123837,A77,PRODUCT12,201626,4815.0,4815.0,2016,26,4530.533333,4837.153846,1.062789
123838,A77,PRODUCT12,201627,3002.0,3002.0,2016,27,4518.466667,4837.153846,0.664385
123839,A77,PRODUCT12,201628,3319.0,3319.0,2016,28,4527.000000,4837.153846,0.733157
123840,A77,PRODUCT12,201629,4200.0,4200.0,2016,29,4528.533333,4837.153846,0.927453
123841,A77,PRODUCT12,201630,7120.0,7120.0,2016,30,4402.866667,4837.153846,1.617128
123842,A77,PRODUCT12,201631,6345.0,6345.0,2016,31,4418.533333,4837.153846,1.435997
123843,A77,PRODUCT12,201632,5863.0,5863.0,2016,32,5182.466667,4837.153846,1.131315
123844,A77,PRODUCT12,201633,4211.0,4211.0,2016,33,5145.466667,4837.153846,0.818390
123845,A77,PRODUCT12,201634,4019.0,4019.0,2016,34,5091.800000,4837.153846,0.789308
123846,A77,PRODUCT12,201635,3624.0,3624.0,2016,35,5177.800000,4837.153846,0.699911
123847,A77,PRODUCT12,201636,3742.0,3742.0,2016,36,5340.533333,4837.153846,0.700679
123848,A77,PRODUCT12,201637,3002.0,3002.0,2016,37,5334.466667,4837.153846,0.562755
123849,A77,PRODUCT12,201638,5583.0,5583.0,2016,38,5160.200000,4837.153846,1.081935
123850,A77,PRODUCT12,201639,14734.0,14734.0,2016,39,5020.866667,4837.153846,2.934553
123851,A77,PRODUCT12,201640,3603.0,3603.0,2016,40,4868.266667,4837.153846,0.740099
123852,A77,PRODUCT12,201641,4010.0,4010.0,2016,41,4864.333333,4837.153846,0.824368
123853,A77,PRODUCT12,201642,4292.0,4292.0,2016,42,4935.466667,4837.153846,0.869624
123854,A77,PRODUCT12,201643,5760.0,5760.0,2016,43,5083.600000,4837.153846,1.133055
123855,A77,PRODUCT12,201644,4109.0,4109.0,2016,44,5163.000000,4837.153846,0.795855
123856,A77,PRODUCT12,201645,4506.0,4506.0,2016,45,5466.266667,4837.153846,0.824329
123857,A77,PRODUCT12,201646,4255.0,4255.0,2016,46,5457.928571,4837.153846,0.779600
123858,A77,PRODUCT12,201647,3574.0,3574.0,2016,47,4744.384615,4837.153846,0.753312
123859,A77,PRODUCT12,201648,4152.0,4152.0,2016,48,4839.500000,4837.153846,0.857940
123860,A77,PRODUCT12,201649,5086.0,5086.0,2016,49,4914.909091,4837.153846,1.034811
123861,A77,PRODUCT12,201650,5846.0,5846.0,2016,50,4977.200000,4837.153846,1.174556
123862,A77,PRODUCT12,201651,4933.0,4933.0,2016,51,4890.222222,4837.153846,1.008748
123863,A77,PRODUCT12,201652,7551.0,7551.0,2016,52,4987.875000,4837.153846,1.513871

In [43]:
len(list(groupDataSet.groups))

794

In [121]:
list(groupDataSet.groups)[0]

('A00', 'PRODUCT34')

In [44]:
oneGroup = groupDataSet.get_group(list(groupDataSet.groups)[2])
oneGroup

,Unnamed: 0,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,QTY_MEAN_YEAR,SEASONALITY
312,312,A00,PRODUCT59,201401,9988.0,9988.0,2014,1,6299.933333,27418.692308,1.585414
313,313,A00,PRODUCT59,201402,9005.0,9005.0,2014,2,7296.333333,27418.692308,1.234182
314,314,A00,PRODUCT59,201403,8416.0,8416.0,2014,3,8346.600000,27418.692308,1.008315
315,315,A00,PRODUCT59,201404,8553.0,8553.0,2014,4,9418.600000,27418.692308,0.908097
316,316,A00,PRODUCT59,201405,10355.0,10355.0,2014,5,10564.200000,27418.692308,0.980197
317,317,A00,PRODUCT59,201406,13799.0,13799.0,2014,6,11718.533333,27418.692308,1.177536
318,318,A00,PRODUCT59,201407,17292.0,17292.0,2014,7,13215.533333,27418.692308,1.308460
319,319,A00,PRODUCT59,201408,16369.0,16369.0,2014,8,14681.400000,27418.692308,1.114948
320,320,A00,PRODUCT59,201409,15047.0,15047.0,2014,9,15328.200000,27418.692308,0.981655
321,321,A00,PRODUCT59,201410,15895.0,15895.0,2014,10,15913.933333,27418.692308,0.998810
322,322,A00,PRODUCT59,201411,16255.0,16255.0,2014,11,16449.866667,27418.692308,0.988154
323,323,A00,PRODUCT59,201412,17339.0,17339.0,2014,12,17021.866667,27418.692308,1.018631
324,324,A00,PRODUCT59,201413,17419.0,17419.0,2014,13,17591.600000,27418.692308,0.990188
325,325,A00,PRODUCT59,201414,22482.0,22482.0,2014,14,18080.666667,27418.692308,1.243428
326,326,A00,PRODUCT59,201415,22007.0,22007.0,2014,15,18424.866667,27418.692308,1.194418
327,327,A00,PRODUCT59,201416,19690.0,19690.0,2014,16,19024.533333,27418.692308,1.034979
328,328,A00,PRODUCT59,201417,17791.0,17791.0,2014,17,19712.600000,27418.692308,0.902519
329,329,A00,PRODUCT59,201418,16455.0,16455.0,2014,18,20236.333333,27418.692308,0.813141
330,330,A00,PRODUCT59,201419,17133.0,17133.0,2014,19,20870.800000,27418.692308,0.820908
331,331,A00,PRODUCT59,201420,18901.0,18901.0,2014,20,21417.066667,27418.692308,0.882520
332,332,A00,PRODUCT59,201421,21135.0,21135.0,2014,21,22022.866667,27418.692308,0.959684
333,333,A00,PRODUCT59,201422,22455.0,22455.0,2014,22,22309.066667,27418.692308,1.006541
334,334,A00,PRODUCT59,201423,25364.0,25364.0,2014,23,22999.533333,27418.692308,1.102805
335,335,A00,PRODUCT59,201424,25368.0,25368.0,2014,24,23753.400000,27418.692308,1.067973
336,336,A00,PRODUCT59,201425,23751.0,23751.0,2014,25,24763.466667,27418.692308,0.959115
337,337,A00,PRODUCT59,201426,25772.0,25772.0,2014,26,25951.400000,27418.692308,0.993087
338,338,A00,PRODUCT59,201427,25533.0,25533.0,2014,27,27339.800000,27418.692308,0.933913
339,339,A00,PRODUCT59,201428,26506.0,26506.0,2014,28,28811.000000,27418.692308,0.919996
340,340,A00,PRODUCT59,201429,26775.0,26775.0,2014,29,30207.466667,27418.692308,0.886370
341,341,A00,PRODUCT59,201430,32364.0,32364.0,2014,30,31436.266667,27418.692308,1.029512
...,...,...,...,...,...,...,...,...,...,...,...
438,438,A00,PRODUCT59,201623,22650.0,22650.0,2016,23,26879.333333,28213.173077,0.842655
439,439,A00,PRODUCT59,201624,27021.0,27021.0,2016,24,26425.066667,28213.173077,1.022552
440,440,A00,PRODUCT59,201625,22426.0,22426.0,2016,25,26157.466667,28213.173077,0.857346
441,441,A00,PRODUCT59,201626,32988.0,32988.0,2016,26,25488.800000,28213.173077,1.294215
442,442,A00,PRODUCT59,201627,29813.0,29813.0,2016,27,24578.533333,28213.173077,1.212969
443,443,A00,PRODUCT59,201628,28125.0,28125.0,2016,28,24070.133333,28213.173077,1.168460
444,444,A00,PRODUCT59,201629,24441.0,24441.0,2016,29,23711.733333,28213.173077,1.030756
445,445,A00,PRODUCT59,201630,23822.0,23822.0,2016,30,23058.466667,28213.173077,1.033113
446,446,A00,PRODUCT59,201631,24008.0,24008.0,2016,31,22913.866667,28213.173077,1.047750
447,447,A00,PRODUCT59,201632,21644.0,21644.0,2016,32,22518.066667,28213.173077,0.961184
448,448,A00,PRODUCT59,201633,18376.0,18376.0,2016,33,22515.133333,28213.173077,0.816162
449,449,A00,PRODUCT59,201634,15529.0,15529.0,2016,34,21273.133333,28213.173077,0.729982
450,450,A00,PRODUCT59,201635,18000.0,18000.0,2016,35,20501.733333,28213.173077,0.877975
451,451,A00,PRODUCT59,201636,20378.0,20378.0,2016,36,19649.200000,28213.173077,1.037091
452,452,A00,PRODUCT59,201637,16656.0,16656.0,2016,37,19312.333333,28213.173077,0.862454
453,453,A00,PRODUCT59,201638,20481.0,20481.0,2016,38,19162.000000,28213.173077,1.068834
454,454,A00,PRODUCT59,201639,21084.0,21084.0,2016,39,18782.400000,28213.173077,1.122540
455,455,A00,PRODUCT59,201640,22382.0,22382.0,2016,40,18655.000000,28213.173077,1.199786
456,456,A00,PRODUCT59,201641,14358.0,14358.0,2016,41,18638.400000,28213.173077,0.770345
457,457,A00,PRODUCT59,201642,18242.0,18242.0,2016,42,19136.000000,28213.173077,0.953282
458,458,A00,PRODUCT59,201643,15337.0,15337.0,2016,43,19726.266667,28213.173077,0.777491
459,459,A00,PRODUCT59,201644,19388.0,19388.0,2016,44,20383.533333,28213.173077,0.951160
460,460,A00,PRODUCT59,201645,21567.0,21567.0,2016,45,21507.200000,28213.173077,1.002780
461,461,A00,PRODUCT59,201646,18314.0,18314.0,2016,46,21082.800000,28213.173077,0.868670
462,462,A00,PRODUCT59,201647,19733.0,19733.0,2016,47,20288.466667,28213.173077,0.972622
463,463,A00,PRODUCT59,201648,18127.0,18127.0,2016,48,20219.666667,28213.173077,0.896503
464,464,A00,PRODUCT59,201649,22993.0,22993.0,2016,49,19892.933333,28213.173077,1.155838
465,465,A00,PRODUCT59,201650,26854.0,26854.0,2016,50,19360.400000,28213.173077,1.387058
466,466,A00,PRODUCT59,201651,30237.0,30237.0,2016,51,19026.400000,28213.173077,1.589213
467,467,A00,PRODUCT59,201652,33511.0,33511.0,2016,52,18372.600000,28213.173077,1.823966

In [45]:
groupDataSet

In [46]:
indexGroupData = oneGroup.reset_index(drop = True)

In [47]:
indexGroupData

,Unnamed: 0,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,QTY_MEAN_YEAR,SEASONALITY
0,312,A00,PRODUCT59,201401,9988.0,9988.0,2014,1,6299.933333,27418.692308,1.585414
1,313,A00,PRODUCT59,201402,9005.0,9005.0,2014,2,7296.333333,27418.692308,1.234182
2,314,A00,PRODUCT59,201403,8416.0,8416.0,2014,3,8346.600000,27418.692308,1.008315
3,315,A00,PRODUCT59,201404,8553.0,8553.0,2014,4,9418.600000,27418.692308,0.908097
4,316,A00,PRODUCT59,201405,10355.0,10355.0,2014,5,10564.200000,27418.692308,0.980197
5,317,A00,PRODUCT59,201406,13799.0,13799.0,2014,6,11718.533333,27418.692308,1.177536
6,318,A00,PRODUCT59,201407,17292.0,17292.0,2014,7,13215.533333,27418.692308,1.308460
7,319,A00,PRODUCT59,201408,16369.0,16369.0,2014,8,14681.400000,27418.692308,1.114948
8,320,A00,PRODUCT59,201409,15047.0,15047.0,2014,9,15328.200000,27418.692308,0.981655
9,321,A00,PRODUCT59,201410,15895.0,15895.0,2014,10,15913.933333,27418.692308,0.998810
10,322,A00,PRODUCT59,201411,16255.0,16255.0,2014,11,16449.866667,27418.692308,0.988154
11,323,A00,PRODUCT59,201412,17339.0,17339.0,2014,12,17021.866667,27418.692308,1.018631
12,324,A00,PRODUCT59,201413,17419.0,17419.0,2014,13,17591.600000,27418.692308,0.990188
13,325,A00,PRODUCT59,201414,22482.0,22482.0,2014,14,18080.666667,27418.692308,1.243428
14,326,A00,PRODUCT59,201415,22007.0,22007.0,2014,15,18424.866667,27418.692308,1.194418
15,327,A00,PRODUCT59,201416,19690.0,19690.0,2014,16,19024.533333,27418.692308,1.034979
16,328,A00,PRODUCT59,201417,17791.0,17791.0,2014,17,19712.600000,27418.692308,0.902519
17,329,A00,PRODUCT59,201418,16455.0,16455.0,2014,18,20236.333333,27418.692308,0.813141
18,330,A00,PRODUCT59,201419,17133.0,17133.0,2014,19,20870.800000,27418.692308,0.820908
19,331,A00,PRODUCT59,201420,18901.0,18901.0,2014,20,21417.066667,27418.692308,0.882520
20,332,A00,PRODUCT59,201421,21135.0,21135.0,2014,21,22022.866667,27418.692308,0.959684
21,333,A00,PRODUCT59,201422,22455.0,22455.0,2014,22,22309.066667,27418.692308,1.006541
22,334,A00,PRODUCT59,201423,25364.0,25364.0,2014,23,22999.533333,27418.692308,1.102805
23,335,A00,PRODUCT59,201424,25368.0,25368.0,2014,24,23753.400000,27418.692308,1.067973
24,336,A00,PRODUCT59,201425,23751.0,23751.0,2014,25,24763.466667,27418.692308,0.959115
25,337,A00,PRODUCT59,201426,25772.0,25772.0,2014,26,25951.400000,27418.692308,0.993087
26,338,A00,PRODUCT59,201427,25533.0,25533.0,2014,27,27339.800000,27418.692308,0.933913
27,339,A00,PRODUCT59,201428,26506.0,26506.0,2014,28,28811.000000,27418.692308,0.919996
28,340,A00,PRODUCT59,201429,26775.0,26775.0,2014,29,30207.466667,27418.692308,0.886370
29,341,A00,PRODUCT59,201430,32364.0,32364.0,2014,30,31436.266667,27418.692308,1.029512
...,...,...,...,...,...,...,...,...,...,...,...
126,438,A00,PRODUCT59,201623,22650.0,22650.0,2016,23,26879.333333,28213.173077,0.842655
127,439,A00,PRODUCT59,201624,27021.0,27021.0,2016,24,26425.066667,28213.173077,1.022552
128,440,A00,PRODUCT59,201625,22426.0,22426.0,2016,25,26157.466667,28213.173077,0.857346
129,441,A00,PRODUCT59,201626,32988.0,32988.0,2016,26,25488.800000,28213.173077,1.294215
130,442,A00,PRODUCT59,201627,29813.0,29813.0,2016,27,24578.533333,28213.173077,1.212969
131,443,A00,PRODUCT59,201628,28125.0,28125.0,2016,28,24070.133333,28213.173077,1.168460
132,444,A00,PRODUCT59,201629,24441.0,24441.0,2016,29,23711.733333,28213.173077,1.030756
133,445,A00,PRODUCT59,201630,23822.0,23822.0,2016,30,23058.466667,28213.173077,1.033113
134,446,A00,PRODUCT59,201631,24008.0,24008.0,2016,31,22913.866667,28213.173077,1.047750
135,447,A00,PRODUCT59,201632,21644.0,21644.0,2016,32,22518.066667,28213.173077,0.961184
136,448,A00,PRODUCT59,201633,18376.0,18376.0,2016,33,22515.133333,28213.173077,0.816162
137,449,A00,PRODUCT59,201634,15529.0,15529.0,2016,34,21273.133333,28213.173077,0.729982
138,450,A00,PRODUCT59,201635,18000.0,18000.0,2016,35,20501.733333,28213.173077,0.877975
139,451,A00,PRODUCT59,201636,20378.0,20378.0,2016,36,19649.200000,28213.173077,1.037091
140,452,A00,PRODUCT59,201637,16656.0,16656.0,2016,37,19312.333333,28213.173077,0.862454
141,453,A00,PRODUCT59,201638,20481.0,20481.0,2016,38,19162.000000,28213.173077,1.068834
142,454,A00,PRODUCT59,201639,21084.0,21084.0,2016,39,18782.400000,28213.173077,1.122540
143,455,A00,PRODUCT59,201640,22382.0,22382.0,2016,40,18655.000000,28213.173077,1.199786
144,456,A00,PRODUCT59,201641,14358.0,14358.0,2016,41,18638.400000,28213.173077,0.770345
145,457,A00,PRODUCT59,201642,18242.0,18242.0,2016,42,19136.000000,28213.173077,0.953282
146,458,A00,PRODUCT59,201643,15337.0,15337.0,2016,43,19726.266667,28213.173077,0.777491
147,459,A00,PRODUCT59,201644,19388.0,19388.0,2016,44,20383.533333,28213.173077,0.951160
148,460,A00,PRODUCT59,201645,21567.0,21567.0,2016,45,21507.200000,28213.173077,1.002780
149,461,A00,PRODUCT59,201646,18314.0,18314.0,2016,46,21082.800000,28213.173077,0.868670
150,462,A00,PRODUCT59,201647,19733.0,19733.0,2016,47,20288.466667,28213.173077,0.972622
151,463,A00,PRODUCT59,201648,18127.0,18127.0,2016,48,20219.666667,28213.173077,0.896503
152,464,A00,PRODUCT59,201649,22993.0,22993.0,2016,49,19892.933333,28213.173077,1.155838
153,465,A00,PRODUCT59,201650,26854.0,26854.0,2016,50,19360.400000,28213.173077,1.387058
154,466,A00,PRODUCT59,201651,30237.0,30237.0,2016,51,19026.400000,28213.173077,1.589213
155,467,A00,PRODUCT59,201652,33511.0,33511.0,2016,52,18372.600000,28213.173077,1.823966

In [48]:
testData

,Unnamed: 0,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,QTY_MEAN_YEAR,SEASONALITY
0,0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000,275.961538,1.271154
1,1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444,275.961538,1.319870
2,2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000,275.961538,1.118421
3,3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636,275.961538,1.056890
4,4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000,275.961538,1.051452
5,5,A00,PRODUCT34,201406,423.0,423.0,2014,6,480.230769,275.961538,0.880827
6,6,A00,PRODUCT34,201407,407.0,407.0,2014,7,468.214286,275.961538,0.869260
7,7,A00,PRODUCT34,201408,364.0,364.0,2014,8,456.666667,275.961538,0.797080
8,8,A00,PRODUCT34,201409,470.0,470.0,2014,9,431.533333,275.961538,1.089140
9,9,A00,PRODUCT34,201410,538.0,538.0,2014,10,402.066667,275.961538,1.338087
10,10,A00,PRODUCT34,201411,369.0,369.0,2014,11,375.533333,275.961538,0.982603
11,11,A00,PRODUCT34,201412,352.0,352.0,2014,12,350.800000,275.961538,1.003421
12,12,A00,PRODUCT34,201413,354.0,354.0,2014,13,325.733333,275.961538,1.086779
13,13,A00,PRODUCT34,201414,312.0,312.0,2014,14,305.266667,275.961538,1.022057
14,14,A00,PRODUCT34,201415,295.0,295.0,2014,15,284.666667,275.961538,1.036300
15,15,A00,PRODUCT34,201416,284.0,284.0,2014,16,265.933333,275.961538,1.067937
16,16,A00,PRODUCT34,201417,237.0,237.0,2014,17,239.333333,275.961538,0.990251
17,17,A00,PRODUCT34,201418,180.0,180.0,2014,18,207.800000,275.961538,0.866218
18,18,A00,PRODUCT34,201419,161.0,161.0,2014,19,187.200000,275.961538,0.860043
19,19,A00,PRODUCT34,201420,140.0,140.0,2014,20,169.200000,275.961538,0.827423
20,20,A00,PRODUCT34,201421,116.0,116.0,2014,21,155.666667,275.961538,0.745182
21,21,A00,PRODUCT34,201422,98.0,98.0,2014,22,153.133333,275.961538,0.639965
22,22,A00,PRODUCT34,201423,83.0,83.0,2014,23,168.933333,275.961538,0.491318
23,23,A00,PRODUCT34,201424,71.0,71.0,2014,24,179.933333,275.961538,0.394591
24,24,A00,PRODUCT34,201425,65.0,65.0,2014,25,193.000000,275.961538,0.336788
25,25,A00,PRODUCT34,201426,60.0,60.0,2014,26,205.266667,275.961538,0.292303
26,26,A00,PRODUCT34,201427,82.0,82.0,2014,27,217.600000,275.961538,0.376838
27,27,A00,PRODUCT34,201428,151.0,151.0,2014,28,229.066667,275.961538,0.659197
28,28,A00,PRODUCT34,201429,274.0,274.0,2014,29,237.600000,275.961538,1.153199
29,29,A00,PRODUCT34,201430,532.0,532.0,2014,30,246.200000,275.961538,2.160845
...,...,...,...,...,...,...,...,...,...,...,...
123834,123834,A77,PRODUCT12,201623,5348.0,5348.0,2016,23,4159.933333,4837.153846,1.285598
123835,123835,A77,PRODUCT12,201624,3275.0,3275.0,2016,24,4272.333333,4837.153846,0.766560
123836,123836,A77,PRODUCT12,201625,4158.0,4158.0,2016,25,4435.133333,4837.153846,0.937514
123837,123837,A77,PRODUCT12,201626,4815.0,4815.0,2016,26,4530.533333,4837.153846,1.062789
123838,123838,A77,PRODUCT12,201627,3002.0,3002.0,2016,27,4518.466667,4837.153846,0.664385
123839,123839,A77,PRODUCT12,201628,3319.0,3319.0,2016,28,4527.000000,4837.153846,0.733157
123840,123840,A77,PRODUCT12,201629,4200.0,4200.0,2016,29,4528.533333,4837.153846,0.927453
123841,123841,A77,PRODUCT12,201630,7120.0,7120.0,2016,30,4402.866667,4837.153846,1.617128
123842,123842,A77,PRODUCT12,201631,6345.0,6345.0,2016,31,4418.533333,4837.153846,1.435997
123843,123843,A77,PRODUCT12,201632,5863.0,5863.0,2016,32,5182.466667,4837.153846,1.131315
123844,123844,A77,PRODUCT12,201633,4211.0,4211.0,2016,33,5145.466667,4837.153846,0.818390
123845,123845,A77,PRODUCT12,201634,4019.0,4019.0,2016,34,5091.800000,4837.153846,0.789308
123846,123846,A77,PRODUCT12,201635,3624.0,3624.0,2016,35,5177.800000,4837.153846,0.699911
123847,123847,A77,PRODUCT12,201636,3742.0,3742.0,2016,36,5340.533333,4837.153846,0.700679
123848,123848,A77,PRODUCT12,201637,3002.0,3002.0,2016,37,5334.466667,4837.153846,0.562755
123849,123849,A77,PRODUCT12,201638,5583.0,5583.0,2016,38,5160.200000,4837.153846,1.081935
123850,123850,A77,PRODUCT12,201639,14734.0,14734.0,2016,39,5020.866667,4837.153846,2.934553
123851,123851,A77,PRODUCT12,201640,3603.0,3603.0,2016,40,4868.266667,4837.153846,0.740099
123852,123852,A77,PRODUCT12,201641,4010.0,4010.0,2016,41,4864.333333,4837.153846,0.824368
123853,123853,A77,PRODUCT12,201642,4292.0,4292.0,2016,42,4935.466667,4837.153846,0.869624
123854,123854,A77,PRODUCT12,201643,5760.0,5760.0,2016,43,5083.600000,4837.153846,1.133055
123855,123855,A77,PRODUCT12,201644,4109.0,4109.0,2016,44,5163.000000,4837.153846,0.795855
123856,123856,A77,PRODUCT12,201645,4506.0,4506.0,2016,45,5466.266667,4837.153846,0.824329
123857,123857,A77,PRODUCT12,201646,4255.0,4255.0,2016,46,5457.928571,4837.153846,0.779600
123858,123858,A77,PRODUCT12,201647,3574.0,3574.0,2016,47,4744.384615,4837.153846,0.753312
123859,123859,A77,PRODUCT12,201648,4152.0,4152.0,2016,48,4839.500000,4837.153846,0.857940
123860,123860,A77,PRODUCT12,201649,5086.0,5086.0,2016,49,4914.909091,4837.153846,1.034811
123861,123861,A77,PRODUCT12,201650,5846.0,5846.0,2016,50,4977.200000,4837.153846,1.174556
123862,123862,A77,PRODUCT12,201651,4933.0,4933.0,2016,51,4890.222222,4837.153846,1.008748
123863,123863,A77,PRODUCT12,201652,7551.0,7551.0,2016,52,4987.875000,4837.153846,1.513871

In [49]:
indexGroupData

,Unnamed: 0,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,QTY_MEAN_YEAR,SEASONALITY
0,312,A00,PRODUCT59,201401,9988.0,9988.0,2014,1,6299.933333,27418.692308,1.585414
1,313,A00,PRODUCT59,201402,9005.0,9005.0,2014,2,7296.333333,27418.692308,1.234182
2,314,A00,PRODUCT59,201403,8416.0,8416.0,2014,3,8346.600000,27418.692308,1.008315
3,315,A00,PRODUCT59,201404,8553.0,8553.0,2014,4,9418.600000,27418.692308,0.908097
4,316,A00,PRODUCT59,201405,10355.0,10355.0,2014,5,10564.200000,27418.692308,0.980197
5,317,A00,PRODUCT59,201406,13799.0,13799.0,2014,6,11718.533333,27418.692308,1.177536
6,318,A00,PRODUCT59,201407,17292.0,17292.0,2014,7,13215.533333,27418.692308,1.308460
7,319,A00,PRODUCT59,201408,16369.0,16369.0,2014,8,14681.400000,27418.692308,1.114948
8,320,A00,PRODUCT59,201409,15047.0,15047.0,2014,9,15328.200000,27418.692308,0.981655
9,321,A00,PRODUCT59,201410,15895.0,15895.0,2014,10,15913.933333,27418.692308,0.998810
10,322,A00,PRODUCT59,201411,16255.0,16255.0,2014,11,16449.866667,27418.692308,0.988154
11,323,A00,PRODUCT59,201412,17339.0,17339.0,2014,12,17021.866667,27418.692308,1.018631
12,324,A00,PRODUCT59,201413,17419.0,17419.0,2014,13,17591.600000,27418.692308,0.990188
13,325,A00,PRODUCT59,201414,22482.0,22482.0,2014,14,18080.666667,27418.692308,1.243428
14,326,A00,PRODUCT59,201415,22007.0,22007.0,2014,15,18424.866667,27418.692308,1.194418
15,327,A00,PRODUCT59,201416,19690.0,19690.0,2014,16,19024.533333,27418.692308,1.034979
16,328,A00,PRODUCT59,201417,17791.0,17791.0,2014,17,19712.600000,27418.692308,0.902519
17,329,A00,PRODUCT59,201418,16455.0,16455.0,2014,18,20236.333333,27418.692308,0.813141
18,330,A00,PRODUCT59,201419,17133.0,17133.0,2014,19,20870.800000,27418.692308,0.820908
19,331,A00,PRODUCT59,201420,18901.0,18901.0,2014,20,21417.066667,27418.692308,0.882520
20,332,A00,PRODUCT59,201421,21135.0,21135.0,2014,21,22022.866667,27418.692308,0.959684
21,333,A00,PRODUCT59,201422,22455.0,22455.0,2014,22,22309.066667,27418.692308,1.006541
22,334,A00,PRODUCT59,201423,25364.0,25364.0,2014,23,22999.533333,27418.692308,1.102805
23,335,A00,PRODUCT59,201424,25368.0,25368.0,2014,24,23753.400000,27418.692308,1.067973
24,336,A00,PRODUCT59,201425,23751.0,23751.0,2014,25,24763.466667,27418.692308,0.959115
25,337,A00,PRODUCT59,201426,25772.0,25772.0,2014,26,25951.400000,27418.692308,0.993087
26,338,A00,PRODUCT59,201427,25533.0,25533.0,2014,27,27339.800000,27418.692308,0.933913
27,339,A00,PRODUCT59,201428,26506.0,26506.0,2014,28,28811.000000,27418.692308,0.919996
28,340,A00,PRODUCT59,201429,26775.0,26775.0,2014,29,30207.466667,27418.692308,0.886370
29,341,A00,PRODUCT59,201430,32364.0,32364.0,2014,30,31436.266667,27418.692308,1.029512
...,...,...,...,...,...,...,...,...,...,...,...
126,438,A00,PRODUCT59,201623,22650.0,22650.0,2016,23,26879.333333,28213.173077,0.842655
127,439,A00,PRODUCT59,201624,27021.0,27021.0,2016,24,26425.066667,28213.173077,1.022552
128,440,A00,PRODUCT59,201625,22426.0,22426.0,2016,25,26157.466667,28213.173077,0.857346
129,441,A00,PRODUCT59,201626,32988.0,32988.0,2016,26,25488.800000,28213.173077,1.294215
130,442,A00,PRODUCT59,201627,29813.0,29813.0,2016,27,24578.533333,28213.173077,1.212969
131,443,A00,PRODUCT59,201628,28125.0,28125.0,2016,28,24070.133333,28213.173077,1.168460
132,444,A00,PRODUCT59,201629,24441.0,24441.0,2016,29,23711.733333,28213.173077,1.030756
133,445,A00,PRODUCT59,201630,23822.0,23822.0,2016,30,23058.466667,28213.173077,1.033113
134,446,A00,PRODUCT59,201631,24008.0,24008.0,2016,31,22913.866667,28213.173077,1.047750
135,447,A00,PRODUCT59,201632,21644.0,21644.0,2016,32,22518.066667,28213.173077,0.961184
136,448,A00,PRODUCT59,201633,18376.0,18376.0,2016,33,22515.133333,28213.173077,0.816162
137,449,A00,PRODUCT59,201634,15529.0,15529.0,2016,34,21273.133333,28213.173077,0.729982
138,450,A00,PRODUCT59,201635,18000.0,18000.0,2016,35,20501.733333,28213.173077,0.877975
139,451,A00,PRODUCT59,201636,20378.0,20378.0,2016,36,19649.200000,28213.173077,1.037091
140,452,A00,PRODUCT59,201637,16656.0,16656.0,2016,37,19312.333333,28213.173077,0.862454
141,453,A00,PRODUCT59,201638,20481.0,20481.0,2016,38,19162.000000,28213.173077,1.068834
142,454,A00,PRODUCT59,201639,21084.0,21084.0,2016,39,18782.400000,28213.173077,1.122540
143,455,A00,PRODUCT59,201640,22382.0,22382.0,2016,40,18655.000000,28213.173077,1.199786
144,456,A00,PRODUCT59,201641,14358.0,14358.0,2016,41,18638.400000,28213.173077,0.770345
145,457,A00,PRODUCT59,201642,18242.0,18242.0,2016,42,19136.000000,28213.173077,0.953282
146,458,A00,PRODUCT59,201643,15337.0,15337.0,2016,43,19726.266667,28213.173077,0.777491
147,459,A00,PRODUCT59,201644,19388.0,19388.0,2016,44,20383.533333,28213.173077,0.951160
148,460,A00,PRODUCT59,201645,21567.0,21567.0,2016,45,21507.200000,28213.173077,1.002780
149,461,A00,PRODUCT59,201646,18314.0,18314.0,2016,46,21082.800000,28213.173077,0.868670
150,462,A00,PRODUCT59,201647,19733.0,19733.0,2016,47,20288.466667,28213.173077,0.972622
151,463,A00,PRODUCT59,201648,18127.0,18127.0,2016,48,20219.666667,28213.173077,0.896503
152,464,A00,PRODUCT59,201649,22993.0,22993.0,2016,49,19892.933333,28213.173077,1.155838
153,465,A00,PRODUCT59,201650,26854.0,26854.0,2016,50,19360.400000,28213.173077,1.387058
154,466,A00,PRODUCT59,201651,30237.0,30237.0,2016,51,19026.400000,28213.173077,1.589213
155,467,A00,PRODUCT59,201652,33511.0,33511.0,2016,52,18372.600000,28213.173077,1.823966

In [50]:
indexGroupData['MA2'] = indexGroupData['NEW_QTY'].rolling(window = 5, center = True).mean()
indexGroupData.head()

,Unnamed: 0,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,QTY_MEAN_YEAR,SEASONALITY,MA2
0,312,A00,PRODUCT59,201401,9988.0,9988.0,2014,1,6299.933333,27418.692308,1.585414,NaN
1,313,A00,PRODUCT59,201402,9005.0,9005.0,2014,2,7296.333333,27418.692308,1.234182,NaN
2,314,A00,PRODUCT59,201403,8416.0,8416.0,2014,3,8346.600000,27418.692308,1.008315,9263.4
3,315,A00,PRODUCT59,201404,8553.0,8553.0,2014,4,9418.600000,27418.692308,0.908097,10025.6
4,316,A00,PRODUCT59,201405,10355.0,10355.0,2014,5,10564.200000,27418.692308,0.980197,11683.0

In [51]:
def groupRolling(oneGroup):
    indexGroupData = oneGroup.reset_index(drop = True)
    indexGroupData['MA2'] = indexGroupData.loc.mean(window = 5, center = True).mean()
    return indexGroupData

In [52]:
finalResult = testData.groupby(groupKey2).apply(groupRolling)

In [53]:
finalResult

                        Unnamed: 0 REGIONID    PRODUCT  YEARWEEK      QTY  \
REGIONID PRODUCT
A00      PRODUCT34 0             0      A00  PRODUCT34    201401    661.0
                   1             1      A00  PRODUCT34    201402    679.0
                   2             2      A00  PRODUCT34    201403    578.0
                   3             3      A00  PRODUCT34    201404    532.0
                   4             4      A00  PRODUCT34    201405    516.0
                   5             5      A00  PRODUCT34    201406    423.0
                   6             6      A00  PRODUCT34    201407    407.0
                   7             7      A00  PRODUCT34    201408    364.0
                   8             8      A00  PRODUCT34    201409    470.0
                   9             9      A00  PRODUCT34    201410    538.0
                   10           10      A00  PRODUCT34    201411    369.0
                   11           11      A00  PRODUCT34    201412    352.0
                   12           12      A00  PRODUCT34    201413    354.0
                   13           13      A00  PRODUCT34    201414    312.0
                   14           14      A00  PRODUCT34    201415    295.0
                   15           15      A00  PRODUCT34    201416    284.0
                   16           16      A00  PRODUCT34    201417    237.0
                   17           17      A00  PRODUCT34    201418    180.0
                   18           18      A00  PRODUCT34    201419    161.0
                   19           19      A00  PRODUCT34    201420    140.0
                   20           20      A00  PRODUCT34    201421    116.0
                   21           21      A00  PRODUCT34    201422     98.0
                   22           22      A00  PRODUCT34    201423     83.0
                   23           23      A00  PRODUCT34    201424     71.0
                   24           24      A00  PRODUCT34    201425     65.0
                   25           25      A00  PRODUCT34    201426     60.0
                   26           26      A00  PRODUCT34    201427     82.0
                   27           27      A00  PRODUCT34    201428    151.0
                   28           28      A00  PRODUCT34    201429    274.0
                   29           29      A00  PRODUCT34    201430    532.0
...                            ...      ...        ...       ...      ...
A77      PRODUCT12 126      123834      A77  PRODUCT12    201623   5348.0
                   127      123835      A77  PRODUCT12    201624   3275.0
                   128      123836      A77  PRODUCT12    201625   4158.0
                   129      123837      A77  PRODUCT12    201626   4815.0
                   130      123838      A77  PRODUCT12    201627   3002.0
                   131      123839      A77  PRODUCT12    201628   3319.0
                   132      123840      A77  PRODUCT12    201629   4200.0
                   133      123841      A77  PRODUCT12    201630   7120.0
                   134      123842      A77  PRODUCT12    201631   6345.0
                   135      123843      A77  PRODUCT12    201632   5863.0
                   136      123844      A77  PRODUCT12    201633   4211.0
                   137      123845      A77  PRODUCT12    201634   4019.0
                   138      123846      A77  PRODUCT12    201635   3624.0
                   139      123847      A77  PRODUCT12    201636   3742.0
                   140      123848      A77  PRODUCT12    201637   3002.0
                   141      123849      A77  PRODUCT12    201638   5583.0
                   142      123850      A77  PRODUCT12    201639  14734.0
                   143      123851      A77  PRODUCT12    201640   3603.0
                   144      123852      A77  PRODUCT12    201641   4010.0
                   145      123853      A77  PRODUCT12    201642   4292.0
                   146      123854      A77  PRODUCT12    201643   5760.0
                   147      123855      A77  PRODUCT12    201644   4109.0
                   148      123856      A77  PRODUCT12    201645   4506.0
                   149      123857      A77  PRODUCT12    201646   4255.0
                   150      123858      A77  PRODUCT12    201647   3574.0
                   151      123859      A77  PRODUCT12    201648   4152.0
                   152      123860      A77  PRODUCT12    201649   5086.0
                   153      123861      A77  PRODUCT12    201650   5846.0
                   154      123862      A77  PRODUCT12    201651   4933.0
                   155      123863      A77  PRODUCT12    201652   7551.0

                        NEW_QTY  YEAR  WEEK           MA  QTY_MEAN_YEAR  \
REGIONID PRODUCT
A00      PRODUCT34 0      661.0  2014     1   520.000000     275.961538
                   1      679.0  2014     2   514.444444     275.961538
                   2      578.0  2014     3   516.800000     275.961538
                   3      532.0  2014     4   503.363636     275.961538
                   4      516.0  2014     5   490.750000     275.961538
                   5      423.0  2014     6   480.230769     275.961538
                   6      407.0  2014     7   468.214286     275.961538
                   7      364.0  2014     8   456.666667     275.961538
                   8      470.0  2014     9   431.533333     275.961538
                   9      538.0  2014    10   402.066667     275.961538
                   10     369.0  2014    11   375.533333     275.961538
                   11     352.0  2014    12   350.800000     275.961538
                   12     354.0  2014    13   325.733333     275.961538
                   13     312.0  2014    14   305.266667     275.961538
                   14     295.0  2014    15   284.666667     275.961538
                   15     284.0  2014    16   265.933333     275.961538
                   16     237.0  2014    17   239.333333     275.961538
                   17     180.0  2014    18   207.800000     275.961538
                   18     161.0  2014    19   187.200000     275.961538
                   19     140.0  2014    20   169.200000     275.961538
                   20     116.0  2014    21   155.666667     275.961538
                   21      98.0  2014    22   153.133333     275.961538
                   22      83.0  2014    23   168.933333     275.961538
                   23      71.0  2014    24   179.933333     275.961538
                   24      65.0  2014    25   193.000000     275.961538
                   25      60.0  2014    26   205.266667     275.961538
                   26      82.0  2014    27   217.600000     275.961538
                   27     151.0  2014    28   229.066667     275.961538
                   28     274.0  2014    29   237.600000     275.961538
                   29     532.0  2014    30   246.200000     275.961538
...                         ...   ...   ...          ...            ...
A77      PRODUCT12 126   5348.0  2016    23  4159.933333    4837.153846
                   127   3275.0  2016    24  4272.333333    4837.153846
                   128   4158.0  2016    25  4435.133333    4837.153846
                   129   4815.0  2016    26  4530.533333    4837.153846
                   130   3002.0  2016    27  4518.466667    4837.153846
                   131   3319.0  2016    28  4527.000000    4837.153846
                   132   4200.0  2016    29  4528.533333    4837.153846
                   133   7120.0  2016    30  4402.866667    4837.153846
                   134   6345.0  2016    31  4418.533333    4837.153846
                   135   5863.0  2016    32  5182.466667    4837.153846
                   136   4211.0  2016    33  5145.466667    4837.153846
                   137   4019.0  2016    34  5091.800000    4837.153846
                   138   3624.0  2016    35  5177.800000    4837.153846
                   139   3742.0  2016    36  5340.533333    4837.153846
                   140   3002.0  2016    37  5334.466667    4837.153846
                   141   5583.0  2016    38  5160.200000    4837.153846
                   142  14734.0  2016    39  5020.866667    4837.153846
                   143   3603.0  2016    40  4868.266667    4837.153846
                   144   4010.0  2016    41  4864.333333    4837.153846
                   145   4292.0  2016    42  4935.466667    4837.153846
                   146   5760.0  2016    43  5083.600000    4837.153846
                   147   4109.0  2016    44  5163.000000    4837.153846
                   148   4506.0  2016    45  5466.266667    4837.153846
                   149   4255.0  2016    46  5457.928571    4837.153846
                   150   3574.0  2016    47  4744.384615    4837.153846
                   151   4152.0  2016    48  4839.500000    4837.153846
                   152   5086.0  2016    49  4914.909091    4837.153846
                   153   5846.0  2016    50  4977.200000    4837.153846
                   154   4933.0  2016    51  4890.222222    4837.153846
                   155   7551.0  2016    52  4987.875000    4837.153846

                        SEASONALITY     MA2
REGIONID PRODUCT
A00      PRODUCT34 0       1.271154     NaN
                   1       1.319870     NaN
                   2       1.118421   593.2
                   3       1.056890   545.6
                   4       1.051452   491.2
                   5       0.880827   448.4
                   6       0.869260   436.0
                   7       0.797080   440.4
                   8       1.089140   429.6
                   9       1.338087   418.6
                   10      0.982603   416.6
                   11      1.003421   385.0
                   12      1.086779   336.4
                   13      1.022057   319.4
                   14      1.036300   296.4
                   15      1.067937   261.6
                   16      0.990251   231.4
                   17      0.866218   200.4
                   18      0.860043   166.8
                   19      0.827423   139.0
                   20      0.745182   119.6
                   21      0.639965   101.6
                   22      0.491318    86.6
                   23      0.394591    75.4
                   24      0.336788    72.2
                   25      0.292303    85.8
                   26      0.376838   126.4
                   27      0.659197   219.8
                   28      1.153199   297.6
                   29      2.160845   367.8
...                             ...     ...
A77      PRODUCT12 126     1.285598  4277.4
                   127     0.766560  4496.6
                   128     0.937514  4119.6
                   129     1.062789  3713.8
                   130     0.664385  3898.8
                   131     0.733157  4491.2
                   132     0.927453  4797.2
                   133     1.617128  5369.4
                   134     1.435997  5547.8
                   135     1.131315  5511.6
                   136     0.818390  4812.4
                   137     0.789308  4291.8
                   138     0.699911  3719.6
                   139     0.700679  3994.0
                   140     0.562755  6137.0
                   141     1.081935  6132.8
                   142     2.934553  6186.4
                   143     0.740099  6444.4
                   144     0.824368  6479.8
                   145     0.869624  4354.8
                   146     1.133055  4535.4
                   147     0.795855  4584.4
                   148     0.824329  4440.8
                   149     0.779600  4119.2
                   150     0.753312  4314.6
                   151     0.857940  4582.6
                   152     1.034811  4718.2
                   153     1.174556  5513.6
                   154     1.008748     NaN
                   155     1.513871     NaN

[123864 rows x 12 columns]

In [54]:
groupRolling()

TypeError: groupRolling() missing 1 required positional argument: 'oneGroup'

In [94]:
testData

,Unnamed: 0,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,QTY_MEAN_YEAR,SEASONALITY
0,0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000,275.961538,1.271154
1,1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444,275.961538,1.319870
2,2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000,275.961538,1.118421
3,3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636,275.961538,1.056890
4,4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000,275.961538,1.051452
5,5,A00,PRODUCT34,201406,423.0,423.0,2014,6,480.230769,275.961538,0.880827
6,6,A00,PRODUCT34,201407,407.0,407.0,2014,7,468.214286,275.961538,0.869260
7,7,A00,PRODUCT34,201408,364.0,364.0,2014,8,456.666667,275.961538,0.797080
8,8,A00,PRODUCT34,201409,470.0,470.0,2014,9,431.533333,275.961538,1.089140
9,9,A00,PRODUCT34,201410,538.0,538.0,2014,10,402.066667,275.961538,1.338087
10,10,A00,PRODUCT34,201411,369.0,369.0,2014,11,375.533333,275.961538,0.982603
11,11,A00,PRODUCT34,201412,352.0,352.0,2014,12,350.800000,275.961538,1.003421
12,12,A00,PRODUCT34,201413,354.0,354.0,2014,13,325.733333,275.961538,1.086779
13,13,A00,PRODUCT34,201414,312.0,312.0,2014,14,305.266667,275.961538,1.022057
14,14,A00,PRODUCT34,201415,295.0,295.0,2014,15,284.666667,275.961538,1.036300
15,15,A00,PRODUCT34,201416,284.0,284.0,2014,16,265.933333,275.961538,1.067937
16,16,A00,PRODUCT34,201417,237.0,237.0,2014,17,239.333333,275.961538,0.990251
17,17,A00,PRODUCT34,201418,180.0,180.0,2014,18,207.800000,275.961538,0.866218
18,18,A00,PRODUCT34,201419,161.0,161.0,2014,19,187.200000,275.961538,0.860043
19,19,A00,PRODUCT34,201420,140.0,140.0,2014,20,169.200000,275.961538,0.827423
20,20,A00,PRODUCT34,201421,116.0,116.0,2014,21,155.666667,275.961538,0.745182
21,21,A00,PRODUCT34,201422,98.0,98.0,2014,22,153.133333,275.961538,0.639965
22,22,A00,PRODUCT34,201423,83.0,83.0,2014,23,168.933333,275.961538,0.491318
23,23,A00,PRODUCT34,201424,71.0,71.0,2014,24,179.933333,275.961538,0.394591
24,24,A00,PRODUCT34,201425,65.0,65.0,2014,25,193.000000,275.961538,0.336788
25,25,A00,PRODUCT34,201426,60.0,60.0,2014,26,205.266667,275.961538,0.292303
26,26,A00,PRODUCT34,201427,82.0,82.0,2014,27,217.600000,275.961538,0.376838
27,27,A00,PRODUCT34,201428,151.0,151.0,2014,28,229.066667,275.961538,0.659197
28,28,A00,PRODUCT34,201429,274.0,274.0,2014,29,237.600000,275.961538,1.153199
29,29,A00,PRODUCT34,201430,532.0,532.0,2014,30,246.200000,275.961538,2.160845
...,...,...,...,...,...,...,...,...,...,...,...
123834,123834,A77,PRODUCT12,201623,5348.0,5348.0,2016,23,4159.933333,4837.153846,1.285598
123835,123835,A77,PRODUCT12,201624,3275.0,3275.0,2016,24,4272.333333,4837.153846,0.766560
123836,123836,A77,PRODUCT12,201625,4158.0,4158.0,2016,25,4435.133333,4837.153846,0.937514
123837,123837,A77,PRODUCT12,201626,4815.0,4815.0,2016,26,4530.533333,4837.153846,1.062789
123838,123838,A77,PRODUCT12,201627,3002.0,3002.0,2016,27,4518.466667,4837.153846,0.664385
123839,123839,A77,PRODUCT12,201628,3319.0,3319.0,2016,28,4527.000000,4837.153846,0.733157
123840,123840,A77,PRODUCT12,201629,4200.0,4200.0,2016,29,4528.533333,4837.153846,0.927453
123841,123841,A77,PRODUCT12,201630,7120.0,7120.0,2016,30,4402.866667,4837.153846,1.617128
123842,123842,A77,PRODUCT12,201631,6345.0,6345.0,2016,31,4418.533333,4837.153846,1.435997
123843,123843,A77,PRODUCT12,201632,5863.0,5863.0,2016,32,5182.466667,4837.153846,1.131315
123844,123844,A77,PRODUCT12,201633,4211.0,4211.0,2016,33,5145.466667,4837.153846,0.818390
123845,123845,A77,PRODUCT12,201634,4019.0,4019.0,2016,34,5091.800000,4837.153846,0.789308
123846,123846,A77,PRODUCT12,201635,3624.0,3624.0,2016,35,5177.800000,4837.153846,0.699911
123847,123847,A77,PRODUCT12,201636,3742.0,3742.0,2016,36,5340.533333,4837.153846,0.700679
123848,123848,A77,PRODUCT12,201637,3002.0,3002.0,2016,37,5334.466667,4837.153846,0.562755
123849,123849,A77,PRODUCT12,201638,5583.0,5583.0,2016,38,5160.200000,4837.153846,1.081935
123850,123850,A77,PRODUCT12,201639,14734.0,14734.0,2016,39,5020.866667,4837.153846,2.934553
123851,123851,A77,PRODUCT12,201640,3603.0,3603.0,2016,40,4868.266667,4837.153846,0.740099
123852,123852,A77,PRODUCT12,201641,4010.0,4010.0,2016,41,4864.333333,4837.153846,0.824368
123853,123853,A77,PRODUCT12,201642,4292.0,4292.0,2016,42,4935.466667,4837.153846,0.869624
123854,123854,A77,PRODUCT12,201643,5760.0,5760.0,2016,43,5083.600000,4837.153846,1.133055
123855,123855,A77,PRODUCT12,201644,4109.0,4109.0,2016,44,5163.000000,4837.153846,0.795855
123856,123856,A77,PRODUCT12,201645,4506.0,4506.0,2016,45,5466.266667,4837.153846,0.824329
123857,123857,A77,PRODUCT12,201646,4255.0,4255.0,2016,46,5457.928571,4837.153846,0.779600
123858,123858,A77,PRODUCT12,201647,3574.0,3574.0,2016,47,4744.384615,4837.153846,0.753312
123859,123859,A77,PRODUCT12,201648,4152.0,4152.0,2016,48,4839.500000,4837.153846,0.857940
123860,123860,A77,PRODUCT12,201649,5086.0,5086.0,2016,49,4914.909091,4837.153846,1.034811
123861,123861,A77,PRODUCT12,201650,5846.0,5846.0,2016,50,4977.200000,4837.153846,1.174556
123862,123862,A77,PRODUCT12,201651,4933.0,4933.0,2016,51,4890.222222,4837.153846,1.008748
123863,123863,A77,PRODUCT12,201652,7551.0,7551.0,2016,52,4987.875000,4837.153846,1.513871

In [166]:
def recent4(inputData):
    index = data.reset_index(drop = True)
    
    a = inputData
  

    return index

In [167]:
test1 = testData.groupby(['REGIONID', 'PRODUCT'])
test2 = test1.apply(recent4)
test2

                        Unnamed: 0 REGIONID    PRODUCT  YEARWEEK      QTY  \
REGIONID PRODUCT
A00      PRODUCT34 0             0      A00  PRODUCT34    201401    661.0
                   1             1      A00  PRODUCT34    201402    679.0
                   2             2      A00  PRODUCT34    201403    578.0
                   3             3      A00  PRODUCT34    201404    532.0
                   4             4      A00  PRODUCT34    201405    516.0
                   5             5      A00  PRODUCT34    201406    423.0
                   6             6      A00  PRODUCT34    201407    407.0
                   7             7      A00  PRODUCT34    201408    364.0
                   8             8      A00  PRODUCT34    201409    470.0
                   9             9      A00  PRODUCT34    201410    538.0
                   10           10      A00  PRODUCT34    201411    369.0
                   11           11      A00  PRODUCT34    201412    352.0
                   12           12      A00  PRODUCT34    201413    354.0
                   13           13      A00  PRODUCT34    201414    312.0
                   14           14      A00  PRODUCT34    201415    295.0
                   15           15      A00  PRODUCT34    201416    284.0
                   16           16      A00  PRODUCT34    201417    237.0
                   17           17      A00  PRODUCT34    201418    180.0
                   18           18      A00  PRODUCT34    201419    161.0
                   19           19      A00  PRODUCT34    201420    140.0
                   20           20      A00  PRODUCT34    201421    116.0
                   21           21      A00  PRODUCT34    201422     98.0
                   22           22      A00  PRODUCT34    201423     83.0
                   23           23      A00  PRODUCT34    201424     71.0
                   24           24      A00  PRODUCT34    201425     65.0
                   25           25      A00  PRODUCT34    201426     60.0
                   26           26      A00  PRODUCT34    201427     82.0
                   27           27      A00  PRODUCT34    201428    151.0
                   28           28      A00  PRODUCT34    201429    274.0
                   29           29      A00  PRODUCT34    201430    532.0
...                            ...      ...        ...       ...      ...
A77      PRODUCT12 126      123834      A77  PRODUCT12    201623   5348.0
                   127      123835      A77  PRODUCT12    201624   3275.0
                   128      123836      A77  PRODUCT12    201625   4158.0
                   129      123837      A77  PRODUCT12    201626   4815.0
                   130      123838      A77  PRODUCT12    201627   3002.0
                   131      123839      A77  PRODUCT12    201628   3319.0
                   132      123840      A77  PRODUCT12    201629   4200.0
                   133      123841      A77  PRODUCT12    201630   7120.0
                   134      123842      A77  PRODUCT12    201631   6345.0
                   135      123843      A77  PRODUCT12    201632   5863.0
                   136      123844      A77  PRODUCT12    201633   4211.0
                   137      123845      A77  PRODUCT12    201634   4019.0
                   138      123846      A77  PRODUCT12    201635   3624.0
                   139      123847      A77  PRODUCT12    201636   3742.0
                   140      123848      A77  PRODUCT12    201637   3002.0
                   141      123849      A77  PRODUCT12    201638   5583.0
                   142      123850      A77  PRODUCT12    201639  14734.0
                   143      123851      A77  PRODUCT12    201640   3603.0
                   144      123852      A77  PRODUCT12    201641   4010.0
                   145      123853      A77  PRODUCT12    201642   4292.0
                   146      123854      A77  PRODUCT12    201643   5760.0
                   147      123855      A77  PRODUCT12    201644   4109.0
                   148      123856      A77  PRODUCT12    201645   4506.0
                   149      123857      A77  PRODUCT12    201646   4255.0
                   150      123858      A77  PRODUCT12    201647   3574.0
                   151      123859      A77  PRODUCT12    201648   4152.0
                   152      123860      A77  PRODUCT12    201649   5086.0
                   153      123861      A77  PRODUCT12    201650   5846.0
                   154      123862      A77  PRODUCT12    201651   4933.0
                   155      123863      A77  PRODUCT12    201652   7551.0

                        NEW_QTY  YEAR  WEEK           MA  QTY_MEAN_YEAR  \
REGIONID PRODUCT
A00      PRODUCT34 0      661.0  2014     1   520.000000     275.961538
                   1      679.0  2014     2   514.444444     275.961538
                   2      578.0  2014     3   516.800000     275.961538
                   3      532.0  2014     4   503.363636     275.961538
                   4      516.0  2014     5   490.750000     275.961538
                   5      423.0  2014     6   480.230769     275.961538
                   6      407.0  2014     7   468.214286     275.961538
                   7      364.0  2014     8   456.666667     275.961538
                   8      470.0  2014     9   431.533333     275.961538
                   9      538.0  2014    10   402.066667     275.961538
                   10     369.0  2014    11   375.533333     275.961538
                   11     352.0  2014    12   350.800000     275.961538
                   12     354.0  2014    13   325.733333     275.961538
                   13     312.0  2014    14   305.266667     275.961538
                   14     295.0  2014    15   284.666667     275.961538
                   15     284.0  2014    16   265.933333     275.961538
                   16     237.0  2014    17   239.333333     275.961538
                   17     180.0  2014    18   207.800000     275.961538
                   18     161.0  2014    19   187.200000     275.961538
                   19     140.0  2014    20   169.200000     275.961538
                   20     116.0  2014    21   155.666667     275.961538
                   21      98.0  2014    22   153.133333     275.961538
                   22      83.0  2014    23   168.933333     275.961538
                   23      71.0  2014    24   179.933333     275.961538
                   24      65.0  2014    25   193.000000     275.961538
                   25      60.0  2014    26   205.266667     275.961538
                   26      82.0  2014    27   217.600000     275.961538
                   27     151.0  2014    28   229.066667     275.961538
                   28     274.0  2014    29   237.600000     275.961538
                   29     532.0  2014    30   246.200000     275.961538
...                         ...   ...   ...          ...            ...
A77      PRODUCT12 126   5348.0  2016    23  4159.933333    4837.153846
                   127   3275.0  2016    24  4272.333333    4837.153846
                   128   4158.0  2016    25  4435.133333    4837.153846
                   129   4815.0  2016    26  4530.533333    4837.153846
                   130   3002.0  2016    27  4518.466667    4837.153846
                   131   3319.0  2016    28  4527.000000    4837.153846
                   132   4200.0  2016    29  4528.533333    4837.153846
                   133   7120.0  2016    30  4402.866667    4837.153846
                   134   6345.0  2016    31  4418.533333    4837.153846
                   135   5863.0  2016    32  5182.466667    4837.153846
                   136   4211.0  2016    33  5145.466667    4837.153846
                   137   4019.0  2016    34  5091.800000    4837.153846
                   138   3624.0  2016    35  5177.800000    4837.153846
                   139   3742.0  2016    36  5340.533333    4837.153846
                   140   3002.0  2016    37  5334.466667    4837.153846
                   141   5583.0  2016    38  5160.200000    4837.153846
                   142  14734.0  2016    39  5020.866667    4837.153846
                   143   3603.0  2016    40  4868.266667    4837.153846
                   144   4010.0  2016    41  4864.333333    4837.153846
                   145   4292.0  2016    42  4935.466667    4837.153846
                   146   5760.0  2016    43  5083.600000    4837.153846
                   147   4109.0  2016    44  5163.000000    4837.153846
                   148   4506.0  2016    45  5466.266667    4837.153846
                   149   4255.0  2016    46  5457.928571    4837.153846
                   150   3574.0  2016    47  4744.384615    4837.153846
                   151   4152.0  2016    48  4839.500000    4837.153846
                   152   5086.0  2016    49  4914.909091    4837.153846
                   153   5846.0  2016    50  4977.200000    4837.153846
                   154   4933.0  2016    51  4890.222222    4837.153846
                   155   7551.0  2016    52  4987.875000    4837.153846

                        SEASONALITY    nkdsadclk
REGIONID PRODUCT
A00      PRODUCT34 0       1.271154   133.057692
                   1       1.319870   133.057692
                   2       1.118421   133.057692
                   3       1.056890   133.057692
                   4       1.051452   133.057692
                   5       0.880827   133.057692
                   6       0.869260   133.057692
                   7       0.797080   133.057692
                   8       1.089140   133.057692
                   9       1.338087   133.057692
                   10      0.982603   133.057692
                   11      1.003421   133.057692
                   12      1.086779   133.057692
                   13      1.022057   133.057692
                   14      1.036300   133.057692
                   15      1.067937   133.057692
                   16      0.990251   133.057692
                   17      0.866218   133.057692
                   18      0.860043   133.057692
                   19      0.827423   133.057692
                   20      0.745182   133.057692
                   21      0.639965   133.057692
                   22      0.491318   133.057692
                   23      0.394591   133.057692
                   24      0.336788   133.057692
                   25      0.292303   133.057692
                   26      0.376838   133.057692
                   27      0.659197   133.057692
                   28      1.153199   133.057692
                   29      2.160845   133.057692
...                             ...          ...
A77      PRODUCT12 126     1.285598  3471.307692
                   127     0.766560  3471.307692
                   128     0.937514  3471.307692
                   129     1.062789  3471.307692
                   130     0.664385  3471.307692
                   131     0.733157  3471.307692
                   132     0.927453  3471.307692
                   133     1.617128  3471.307692
                   134     1.435997  3471.307692
                   135     1.131315  3471.307692
                   136     0.818390  3471.307692
                   137     0.789308  3471.307692
                   138     0.699911  3471.307692
                   139     0.700679  3471.307692
                   140     0.562755  3471.307692
                   141     1.081935  3471.307692
                   142     2.934553  3471.307692
                   143     0.740099  3471.307692
                   144     0.824368  3471.307692
                   145     0.869624  3471.307692
                   146     1.133055  3471.307692
                   147     0.795855  3471.307692
                   148     0.824329  3471.307692
                   149     0.779600  3471.307692
                   150     0.753312  3471.307692
                   151     0.857940  3471.307692
                   152     1.034811  3471.307692
                   153     1.174556  3471.307692
                   154     1.008748  3471.307692
                   155     1.513871  3471.307692

[123864 rows x 12 columns]

In [131]:
a = [1,2,3,4,5,67,8,9,0]

In [133]:
testPd = pd.DataFrame(a)

In [151]:
result = testPd.loc[5:8,:].values.mean()

In [154]:
testPd.columns = ["predict"]

In [160]:
testPd["predict"].mean()

11.0

In [128]:
test1 = testData.groupby(['REGIONID', 'PRODUCT'])
test1.apply(recent4)

,Unnamed: 0,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,QTY_MEAN_YEAR,SEASONALITY,mean
0,0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000,275.961538,1.271154,NaN
1,1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444,275.961538,1.319870,NaN
2,2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000,275.961538,1.118421,NaN
3,3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636,275.961538,1.056890,NaN
4,4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000,275.961538,1.051452,NaN
5,5,A00,PRODUCT34,201406,423.0,423.0,2014,6,480.230769,275.961538,0.880827,NaN
6,6,A00,PRODUCT34,201407,407.0,407.0,2014,7,468.214286,275.961538,0.869260,NaN
7,7,A00,PRODUCT34,201408,364.0,364.0,2014,8,456.666667,275.961538,0.797080,NaN
8,8,A00,PRODUCT34,201409,470.0,470.0,2014,9,431.533333,275.961538,1.089140,NaN
9,9,A00,PRODUCT34,201410,538.0,538.0,2014,10,402.066667,275.961538,1.338087,NaN
10,10,A00,PRODUCT34,201411,369.0,369.0,2014,11,375.533333,275.961538,0.982603,NaN
11,11,A00,PRODUCT34,201412,352.0,352.0,2014,12,350.800000,275.961538,1.003421,NaN
12,12,A00,PRODUCT34,201413,354.0,354.0,2014,13,325.733333,275.961538,1.086779,NaN
13,13,A00,PRODUCT34,201414,312.0,312.0,2014,14,305.266667,275.961538,1.022057,NaN
14,14,A00,PRODUCT34,201415,295.0,295.0,2014,15,284.666667,275.961538,1.036300,NaN
15,15,A00,PRODUCT34,201416,284.0,284.0,2014,16,265.933333,275.961538,1.067937,NaN
16,16,A00,PRODUCT34,201417,237.0,237.0,2014,17,239.333333,275.961538,0.990251,NaN
17,17,A00,PRODUCT34,201418,180.0,180.0,2014,18,207.800000,275.961538,0.866218,NaN
18,18,A00,PRODUCT34,201419,161.0,161.0,2014,19,187.200000,275.961538,0.860043,NaN
19,19,A00,PRODUCT34,201420,140.0,140.0,2014,20,169.200000,275.961538,0.827423,NaN
20,20,A00,PRODUCT34,201421,116.0,116.0,2014,21,155.666667,275.961538,0.745182,NaN
21,21,A00,PRODUCT34,201422,98.0,98.0,2014,22,153.133333,275.961538,0.639965,NaN
22,22,A00,PRODUCT34,201423,83.0,83.0,2014,23,168.933333,275.961538,0.491318,NaN
23,23,A00,PRODUCT34,201424,71.0,71.0,2014,24,179.933333,275.961538,0.394591,NaN
24,24,A00,PRODUCT34,201425,65.0,65.0,2014,25,193.000000,275.961538,0.336788,NaN
25,25,A00,PRODUCT34,201426,60.0,60.0,2014,26,205.266667,275.961538,0.292303,NaN
26,26,A00,PRODUCT34,201427,82.0,82.0,2014,27,217.600000,275.961538,0.376838,NaN
27,27,A00,PRODUCT34,201428,151.0,151.0,2014,28,229.066667,275.961538,0.659197,NaN
28,28,A00,PRODUCT34,201429,274.0,274.0,2014,29,237.600000,275.961538,1.153199,NaN
29,29,A00,PRODUCT34,201430,532.0,532.0,2014,30,246.200000,275.961538,2.160845,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
123834,123834,A77,PRODUCT12,201623,5348.0,5348.0,2016,23,4159.933333,4837.153846,1.285598,NaN
123835,123835,A77,PRODUCT12,201624,3275.0,3275.0,2016,24,4272.333333,4837.153846,0.766560,NaN
123836,123836,A77,PRODUCT12,201625,4158.0,4158.0,2016,25,4435.133333,4837.153846,0.937514,NaN
123837,123837,A77,PRODUCT12,201626,4815.0,4815.0,2016,26,4530.533333,4837.153846,1.062789,NaN
123838,123838,A77,PRODUCT12,201627,3002.0,3002.0,2016,27,4518.466667,4837.153846,0.664385,NaN
123839,123839,A77,PRODUCT12,201628,3319.0,3319.0,2016,28,4527.000000,4837.153846,0.733157,NaN
123840,123840,A77,PRODUCT12,201629,4200.0,4200.0,2016,29,4528.533333,4837.153846,0.927453,NaN
123841,123841,A77,PRODUCT12,201630,7120.0,7120.0,2016,30,4402.866667,4837.153846,1.617128,NaN
123842,123842,A77,PRODUCT12,201631,6345.0,6345.0,2016,31,4418.533333,4837.153846,1.435997,NaN
123843,123843,A77,PRODUCT12,201632,5863.0,5863.0,2016,32,5182.466667,4837.153846,1.131315,NaN
123844,123844,A77,PRODUCT12,201633,4211.0,4211.0,2016,33,5145.466667,4837.153846,0.818390,NaN
123845,123845,A77,PRODUCT12,201634,4019.0,4019.0,2016,34,5091.800000,4837.153846,0.789308,NaN
123846,123846,A77,PRODUCT12,201635,3624.0,3624.0,2016,35,5177.800000,4837.153846,0.699911,NaN
123847,123847,A77,PRODUCT12,201636,3742.0,3742.0,2016,36,5340.533333,4837.153846,0.700679,NaN
123848,123848,A77,PRODUCT12,201637,3002.0,3002.0,2016,37,5334.466667,4837.153846,0.562755,NaN
123849,123849,A77,PRODUCT12,201638,5583.0,5583.0,2016,38,5160.200000,4837.153846,1.081935,NaN
123850,123850,A77,PRODUCT12,201639,14734.0,14734.0,2016,39,5020.866667,4837.153846,2.934553,NaN
123851,123851,A77,PRODUCT12,201640,3603.0,3603.0,2016,40,4868.266667,4837.153846,0.740099,NaN
123852,123852,A77,PRODUCT12,201641,4010.0,4010.0,2016,41,4864.333333,4837.153846,0.824368,NaN
123853,123853,A77,PRODUCT12,201642,4292.0,4292.0,2016,42,4935.466667,4837.153846,0.869624,NaN
123854,123854,A77,PRODUCT12,201643,5760.0,5760.0,2016,43,5083.600000,4837.153846,1.133055,NaN
123855,123855,A77,PRODUCT12,201644,4109.0,4109.0,2016,44,5163.000000,4837.153846,0.795855,NaN
123856,123856,A77,PRODUCT12,201645,4506.0,4506.0,2016,45,5466.266667,4837.153846,0.824329,NaN
123857,123857,A77,PRODUCT12,201646,4255.0,4255.0,2016,46,5457.928571,4837.153846,0.779600,NaN
123858,123858,A77,PRODUCT12,201647,3574.0,3574.0,2016,47,4744.384615,4837.153846,0.753312,NaN
123859,123859,A77,PRODUCT12,201648,4152.0,4152.0,2016,48,4839.500000,4837.153846,0.857940,NaN
123860,123860,A77,PRODUCT12,201649,5086.0,5086.0,2016,49,4914.909091,4837.153846,1.034811,NaN
123861,123861,A77,PRODUCT12,201650,5846.0,5846.0,2016,50,4977.200000,4837.153846,1.174556,NaN
123862,123862,A77,PRODUCT12,201651,4933.0,4933.0,2016,51,4890.222222,4837.153846,1.008748,NaN
123863,123863,A77,PRODUCT12,201652,7551.0,7551.0,2016,52,4987.875000,4837.153846,1.513871,NaN

In [103]:
test1 = testData.groupby(['REGIONID', 'PRODUCT'])
test1.head()
test2 = test1.apply(recent)
test2
# test2 = test1.apply(recent)
# test2.head()

                        Unnamed: 0 REGIONID    PRODUCT  YEARWEEK      QTY  \
REGIONID PRODUCT
A00      PRODUCT34 0             0      A00  PRODUCT34    201401    661.0
                   1             1      A00  PRODUCT34    201402    679.0
                   2             2      A00  PRODUCT34    201403    578.0
                   3             3      A00  PRODUCT34    201404    532.0
                   4             4      A00  PRODUCT34    201405    516.0
                   5             5      A00  PRODUCT34    201406    423.0
                   6             6      A00  PRODUCT34    201407    407.0
                   7             7      A00  PRODUCT34    201408    364.0
                   8             8      A00  PRODUCT34    201409    470.0
                   9             9      A00  PRODUCT34    201410    538.0
                   10           10      A00  PRODUCT34    201411    369.0
                   11           11      A00  PRODUCT34    201412    352.0
                   12           12      A00  PRODUCT34    201413    354.0
                   13           13      A00  PRODUCT34    201414    312.0
                   14           14      A00  PRODUCT34    201415    295.0
                   15           15      A00  PRODUCT34    201416    284.0
                   16           16      A00  PRODUCT34    201417    237.0
                   17           17      A00  PRODUCT34    201418    180.0
                   18           18      A00  PRODUCT34    201419    161.0
                   19           19      A00  PRODUCT34    201420    140.0
                   20           20      A00  PRODUCT34    201421    116.0
                   21           21      A00  PRODUCT34    201422     98.0
                   22           22      A00  PRODUCT34    201423     83.0
                   23           23      A00  PRODUCT34    201424     71.0
                   24           24      A00  PRODUCT34    201425     65.0
                   25           25      A00  PRODUCT34    201426     60.0
                   26           26      A00  PRODUCT34    201427     82.0
                   27           27      A00  PRODUCT34    201428    151.0
                   28           28      A00  PRODUCT34    201429    274.0
                   29           29      A00  PRODUCT34    201430    532.0
...                            ...      ...        ...       ...      ...
A77      PRODUCT12 126      123834      A77  PRODUCT12    201623   5348.0
                   127      123835      A77  PRODUCT12    201624   3275.0
                   128      123836      A77  PRODUCT12    201625   4158.0
                   129      123837      A77  PRODUCT12    201626   4815.0
                   130      123838      A77  PRODUCT12    201627   3002.0
                   131      123839      A77  PRODUCT12    201628   3319.0
                   132      123840      A77  PRODUCT12    201629   4200.0
                   133      123841      A77  PRODUCT12    201630   7120.0
                   134      123842      A77  PRODUCT12    201631   6345.0
                   135      123843      A77  PRODUCT12    201632   5863.0
                   136      123844      A77  PRODUCT12    201633   4211.0
                   137      123845      A77  PRODUCT12    201634   4019.0
                   138      123846      A77  PRODUCT12    201635   3624.0
                   139      123847      A77  PRODUCT12    201636   3742.0
                   140      123848      A77  PRODUCT12    201637   3002.0
                   141      123849      A77  PRODUCT12    201638   5583.0
                   142      123850      A77  PRODUCT12    201639  14734.0
                   143      123851      A77  PRODUCT12    201640   3603.0
                   144      123852      A77  PRODUCT12    201641   4010.0
                   145      123853      A77  PRODUCT12    201642   4292.0
                   146      123854      A77  PRODUCT12    201643   5760.0
                   147      123855      A77  PRODUCT12    201644   4109.0
                   148      123856      A77  PRODUCT12    201645   4506.0
                   149      123857      A77  PRODUCT12    201646   4255.0
                   150      123858      A77  PRODUCT12    201647   3574.0
                   151      123859      A77  PRODUCT12    201648   4152.0
                   152      123860      A77  PRODUCT12    201649   5086.0
                   153      123861      A77  PRODUCT12    201650   5846.0
                   154      123862      A77  PRODUCT12    201651   4933.0
                   155      123863      A77  PRODUCT12    201652   7551.0

                        NEW_QTY  YEAR  WEEK           MA  QTY_MEAN_YEAR  \
REGIONID PRODUCT
A00      PRODUCT34 0      661.0  2014     1   520.000000     275.961538
                   1      679.0  2014     2   514.444444     275.961538
                   2      578.0  2014     3   516.800000     275.961538
                   3      532.0  2014     4   503.363636     275.961538
                   4      516.0  2014     5   490.750000     275.961538
                   5      423.0  2014     6   480.230769     275.961538
                   6      407.0  2014     7   468.214286     275.961538
                   7      364.0  2014     8   456.666667     275.961538
                   8      470.0  2014     9   431.533333     275.961538
                   9      538.0  2014    10   402.066667     275.961538
                   10     369.0  2014    11   375.533333     275.961538
                   11     352.0  2014    12   350.800000     275.961538
                   12     354.0  2014    13   325.733333     275.961538
                   13     312.0  2014    14   305.266667     275.961538
                   14     295.0  2014    15   284.666667     275.961538
                   15     284.0  2014    16   265.933333     275.961538
                   16     237.0  2014    17   239.333333     275.961538
                   17     180.0  2014    18   207.800000     275.961538
                   18     161.0  2014    19   187.200000     275.961538
                   19     140.0  2014    20   169.200000     275.961538
                   20     116.0  2014    21   155.666667     275.961538
                   21      98.0  2014    22   153.133333     275.961538
                   22      83.0  2014    23   168.933333     275.961538
                   23      71.0  2014    24   179.933333     275.961538
                   24      65.0  2014    25   193.000000     275.961538
                   25      60.0  2014    26   205.266667     275.961538
                   26      82.0  2014    27   217.600000     275.961538
                   27     151.0  2014    28   229.066667     275.961538
                   28     274.0  2014    29   237.600000     275.961538
                   29     532.0  2014    30   246.200000     275.961538
...                         ...   ...   ...          ...            ...
A77      PRODUCT12 126   5348.0  2016    23  4159.933333    4837.153846
                   127   3275.0  2016    24  4272.333333    4837.153846
                   128   4158.0  2016    25  4435.133333    4837.153846
                   129   4815.0  2016    26  4530.533333    4837.153846
                   130   3002.0  2016    27  4518.466667    4837.153846
                   131   3319.0  2016    28  4527.000000    4837.153846
                   132   4200.0  2016    29  4528.533333    4837.153846
                   133   7120.0  2016    30  4402.866667    4837.153846
                   134   6345.0  2016    31  4418.533333    4837.153846
                   135   5863.0  2016    32  5182.466667    4837.153846
                   136   4211.0  2016    33  5145.466667    4837.153846
                   137   4019.0  2016    34  5091.800000    4837.153846
                   138   3624.0  2016    35  5177.800000    4837.153846
                   139   3742.0  2016    36  5340.533333    4837.153846
                   140   3002.0  2016    37  5334.466667    4837.153846
                   141   5583.0  2016    38  5160.200000    4837.153846
                   142  14734.0  2016    39  5020.866667    4837.153846
                   143   3603.0  2016    40  4868.266667    4837.153846
                   144   4010.0  2016    41  4864.333333    4837.153846
                   145   4292.0  2016    42  4935.466667    4837.153846
                   146   5760.0  2016    43  5083.600000    4837.153846
                   147   4109.0  2016    44  5163.000000    4837.153846
                   148   4506.0  2016    45  5466.266667    4837.153846
                   149   4255.0  2016    46  5457.928571    4837.153846
                   150   3574.0  2016    47  4744.384615    4837.153846
                   151   4152.0  2016    48  4839.500000    4837.153846
                   152   5086.0  2016    49  4914.909091    4837.153846
                   153   5846.0  2016    50  4977.200000    4837.153846
                   154   4933.0  2016    51  4890.222222    4837.153846
                   155   7551.0  2016    52  4987.875000    4837.153846

                        SEASONALITY         mean
REGIONID PRODUCT
A00      PRODUCT34 0       1.271154   564.833333
                   1       1.319870   564.833333
                   2       1.118421   564.833333
                   3       1.056890   564.833333
                   4       1.051452   564.833333
                   5       0.880827   564.833333
                   6       0.869260   564.833333
                   7       0.797080   564.833333
                   8       1.089140   564.833333
                   9       1.338087   564.833333
                   10      0.982603   564.833333
                   11      1.003421   564.833333
                   12      1.086779   564.833333
                   13      1.022057   564.833333
                   14      1.036300   564.833333
                   15      1.067937   564.833333
                   16      0.990251   564.833333
                   17      0.866218   564.833333
                   18      0.860043   564.833333
                   19      0.827423   564.833333
                   20      0.745182   564.833333
                   21      0.639965   564.833333
                   22      0.491318   564.833333
                   23      0.394591   564.833333
                   24      0.336788   564.833333
                   25      0.292303   564.833333
                   26      0.376838   564.833333
                   27      0.659197   564.833333
                   28      1.153199   564.833333
                   29      2.160845   564.833333
...                             ...          ...
A77      PRODUCT12 126     1.285598  2758.666667
                   127     0.766560  2758.666667
                   128     0.937514  2758.666667
                   129     1.062789  2758.666667
                   130     0.664385  2758.666667
                   131     0.733157  2758.666667
                   132     0.927453  2758.666667
                   133     1.617128  2758.666667
                   134     1.435997  2758.666667
                   135     1.131315  2758.666667
                   136     0.818390  2758.666667
                   137     0.789308  2758.666667
                   138     0.699911  2758.666667
                   139     0.700679  2758.666667
                   140     0.562755  2758.666667
                   141     1.081935  2758.666667
                   142     2.934553  2758.666667
                   143     0.740099  2758.666667
                   144     0.824368  2758.666667
                   145     0.869624  2758.666667
                   146     1.133055  2758.666667
                   147     0.795855  2758.666667
                   148     0.824329  2758.666667
                   149     0.779600  2758.666667
                   150     0.753312  2758.666667
                   151     0.857940  2758.666667
                   152     1.034811  2758.666667
                   153     1.174556  2758.666667
                   154     1.008748  2758.666667
                   155     1.513871  2758.666667

[123864 rows x 12 columns]

In [82]:
def recent(data):
    index = data.reset_index(drop = True)
    index['mean'] = index.loc[0:5, ['NEW_QTY']].mean()['NEW_QTY']
    return index

In [75]:
test1.head()

,Unnamed: 0,REGIONID,PRODUCT,YEARWEEK,QTY,NEW_QTY,YEAR,WEEK,MA,QTY_MEAN_YEAR,SEASONALITY
0,0,A00,PRODUCT34,201401,661.0,661.0,2014,1,520.000000,275.961538,1.271154
1,1,A00,PRODUCT34,201402,679.0,679.0,2014,2,514.444444,275.961538,1.319870
2,2,A00,PRODUCT34,201403,578.0,578.0,2014,3,516.800000,275.961538,1.118421
3,3,A00,PRODUCT34,201404,532.0,532.0,2014,4,503.363636,275.961538,1.056890
4,4,A00,PRODUCT34,201405,516.0,516.0,2014,5,490.750000,275.961538,1.051452
156,156,A00,PRODUCT58,201401,0.0,0.0,2014,1,12.600000,2.673077,0.000000
157,157,A00,PRODUCT58,201402,0.0,0.0,2014,2,11.666667,2.673077,0.000000
158,158,A00,PRODUCT58,201403,0.0,0.0,2014,3,11.066667,2.673077,0.000000
159,159,A00,PRODUCT58,201404,0.0,0.0,2014,4,9.933333,2.673077,0.000000
160,160,A00,PRODUCT58,201405,0.0,0.0,2014,5,8.666667,2.673077,0.000000
312,312,A00,PRODUCT59,201401,9988.0,9988.0,2014,1,6299.933333,27418.692308,1.585414
313,313,A00,PRODUCT59,201402,9005.0,9005.0,2014,2,7296.333333,27418.692308,1.234182
314,314,A00,PRODUCT59,201403,8416.0,8416.0,2014,3,8346.600000,27418.692308,1.008315
315,315,A00,PRODUCT59,201404,8553.0,8553.0,2014,4,9418.600000,27418.692308,0.908097
316,316,A00,PRODUCT59,201405,10355.0,10355.0,2014,5,10564.200000,27418.692308,0.980197
468,468,A01,PRODUCT1,201401,14115.0,14115.0,2014,1,17611.866667,8622.461538,0.801448
469,469,A01,PRODUCT1,201402,9169.0,9169.0,2014,2,16993.933333,8622.461538,0.539545
470,470,A01,PRODUCT1,201403,21350.0,21350.0,2014,3,16221.133333,8622.461538,1.316184
471,471,A01,PRODUCT1,201404,9457.0,9457.0,2014,4,15521.666667,8622.461538,0.609277
472,472,A01,PRODUCT1,201405,10254.0,10254.0,2014,5,14502.333333,8622.461538,0.707059
624,624,A01,PRODUCT12,201401,139564.0,139564.0,2014,1,74956.400000,169397.826923,1.861936
625,625,A01,PRODUCT12,201402,109173.0,109173.0,2014,2,84771.266667,169397.826923,1.287854
626,626,A01,PRODUCT12,201403,119281.0,119281.0,2014,3,94422.666667,169397.826923,1.263267
627,627,A01,PRODUCT12,201404,139609.0,139609.0,2014,4,103205.733333,169397.826923,1.352725
628,628,A01,PRODUCT12,201405,167828.0,167828.0,2014,5,111885.333333,169397.826923,1.500000
780,780,A01,PRODUCT14,201401,9844.0,9844.0,2014,1,272854.933333,12495.769231,0.036078
781,781,A01,PRODUCT14,201402,6363.0,6363.0,2014,2,243988.733333,12495.769231,0.026079
782,782,A01,PRODUCT14,201403,8022.0,8022.0,2014,3,133727.400000,12495.769231,0.059988
783,783,A01,PRODUCT14,201404,7562.0,7562.0,2014,4,86875.466667,12495.769231,0.087044
784,784,A01,PRODUCT14,201405,6035.0,6035.0,2014,5,68844.800000,12495.769231,0.087661
...,...,...,...,...,...,...,...,...,...,...,...
122928,122928,A69,PRODUCT59,201401,697.0,697.0,2014,1,276.266667,1570.730769,2.522925
122929,122929,A69,PRODUCT59,201402,559.0,559.0,2014,2,333.800000,1570.730769,1.674655
122930,122930,A69,PRODUCT59,201403,423.0,423.0,2014,3,391.866667,1570.730769,1.079449
122931,122931,A69,PRODUCT59,201404,386.0,386.0,2014,4,459.800000,1570.730769,0.839495
122932,122932,A69,PRODUCT59,201405,311.0,311.0,2014,5,519.800000,1570.730769,0.598307
123084,123084,A70,PRODUCT34,201401,66.0,66.0,2014,1,6655.066667,1455.269231,0.009917
123085,123085,A70,PRODUCT34,201402,84.0,84.0,2014,2,5543.800000,1455.269231,0.015152
123086,123086,A70,PRODUCT34,201403,67.0,67.0,2014,3,4580.733333,1455.269231,0.014626
123087,123087,A70,PRODUCT34,201404,60.0,60.0,2014,4,3664.666667,1455.269231,0.016373
123088,123088,A70,PRODUCT34,201405,46.0,46.0,2014,5,2977.400000,1455.269231,0.015450
123240,123240,A70,PRODUCT58,201401,0.0,0.0,2014,1,951.600000,14.384615,0.000000
123241,123241,A70,PRODUCT58,201402,0.0,0.0,2014,2,785.600000,14.384615,0.000000
123242,123242,A70,PRODUCT58,201403,0.0,0.0,2014,3,660.400000,14.384615,0.000000
123243,123243,A70,PRODUCT58,201404,0.0,0.0,2014,4,545.800000,14.384615,0.000000
123244,123244,A70,PRODUCT58,201405,0.0,0.0,2014,5,369.466667,14.384615,0.000000
123396,123396,A70,PRODUCT59,201401,341.0,341.0,2014,1,194.466667,27002.326923,1.753514
123397,123397,A70,PRODUCT59,201402,334.0,334.0,2014,2,203.400000,27002.326923,1.642085
123398,123398,A70,PRODUCT59,201403,298.0,298.0,2014,3,208.733333,27002.326923,1.427659
123399,123399,A70,PRODUCT59,201404,309.0,309.0,2014,4,251.466667,27002.326923,1.228791
123400,123400,A70,PRODUCT59,201405,351.0,351.0,2014,5,377.600000,27002.326923,0.929555
123552,123552,A77,PRODUCT1,201401,3580.0,3580.0,2014,1,41473.400000,2262.653846,0.086320
123553,123553,A77,PRODUCT1,201402,2465.0,2465.0,2014,2,36635.866667,2262.653846,0.067284
123554,123554,A77,PRODUCT1,201403,2205.0,2205.0,2014,3,31321.733333,2262.653846,0.070398
123555,123555,A77,PRODUCT1,201404,1623.0,1623.0,2014,4,26762.733333,2262.653846,0.060644
123556,123556,A77,PRODUCT1,201405,1482.0,1482.0,2014,5,21258.000000,2262.653846,0.069715
123708,123708,A77,PRODUCT12,201401,3821.0,3821.0,2014,1,3042.800000,2035.788462,1.255751
123709,123709,A77,PRODUCT12,201402,2466.0,2466.0,2014,2,3015.400000,2035.788462,0.817802
123710,123710,A77,PRODUCT12,201403,2401.0,2401.0,2014,3,2956.600000,2035.788462,0.812081
123711,123711,A77,PRODUCT12,201404,2628.0,2628.0,2014,4,2924.800000,2035.788462,0.898523
123712,123712,A77,PRODUCT12,201405,1442.0,1442.0,2014,5,2755.200000,2035.788462,0.523374

In [88]:
a01Data = testData[testData.REGIONID == 'A01']

In [89]:
len(a01Data)

3588

In [90]:
a20Data = testData[testData.REGIONID == 'A20']

In [91]:
len(a20Data)

468

In [92]:
resultConcat = pd.concat([a01Data, a20Data], axis = 0)

In [93]:
len(resultConcat)

4056

In [104]:
test2.to_csv('./test.csv')

TypeError: to_csv() got an unexpected keyword argument 'replace'